### ISSUE TITLE
audion plays for 2 seconds 

### ISSUE THREAD

**Issue by RickyBurton** [MusicPlayerDaemon/MPD#1205] opened 2021-07-13 17:23 UTC
Hi, I hope someone can help. I add a URL, http://ais.absoluteradio.co.uk/absolute80s.aac

Update database and play, but audio plays for around 2 seconds and cuts off. Any guidance would be appreciated.

**Comment by skidoo23** [comment] 2021-07-13 18:47
Could not reprocude with MPD from git master on Debian testing x64. Plays music and commercials with 50 kbit/s - Please have a look at https://mpd.readthedocs.io/en/stable/user.html#troubleshooting

**Comment by RickyBurton** [comment] 2021-07-13 20:35
I don't get what you are saying?

**Comment by skidoo23** [comment] 2021-07-14 10:08
Click on link, read text, follow instructions and post output as a start.

**Comment by MaxKellermann** [comment] 2021-07-16 07:06
Can't reproduce. Since the submitter decided not to post the information they were asked to, I'm closing this.

**Closed by MaxKellermann** 2021-07-16 07:06 UTC
