### ISSUE TITLE
src/archive/plugins/Iso9660ArchivePlugin.cxx:116:32: error: too few arguments to function ‘void _cdio_list_free(CdioList_t*, int, CdioDataFree_t)’

### ISSUE THREAD

**Issue by gerroon** [MusicPlayerDaemon/MPD#201] opened 2018-01-21 18:33 UTC
Hi

I am trying to build Mpd on Debia Testing. This error is from the current git pull. But I had the exact error with the release from the Mpd home page. So  I thought maybe I could try the Github version.

I followed the docs on the Mpd's web site  (https://www.musicpd.org/doc/user/install_source.html)  for building from source. And this is the default ./configure although I get the same problem with various 
config options.

I am using 4.14.0-3-amd64 #1 SMP Debian 4.14.13-1 (2018-01-14) x86_64 GNU/Linux, GNU Make 4.1

gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 7.2.0-19' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 7.2.0 (Debian 7.2.0-19) 

pkg-config is already the newest version (0.29-4+b1)

https://paste.debian.net/1006292/

**Comment by MaxKellermann** [comment] 2018-01-21 18:37
Duplicate of #201

**Comment by MaxKellermann** [comment] 2018-01-21 18:38
Sorry, I was about to write: Duplicate of #173

**Closed by MaxKellermann** 2018-01-21 18:38 UTC

**Comment by gerroon** [comment] 2018-01-21 18:41
Thanks for the follow up.
