### ISSUE TITLE
Unable to seek in track streamed via curl

### ISSUE THREAD

**Issue by madduck** [MusicPlayerDaemon/MPD#825] opened 2020-04-13 10:18 UTC
### Describe the bug

If I am trying to `seek` to a position within a playing track, which is being streamed using `curl`, then the track skips just a little, but continues pretty much at the same place, i.e. the seek is unsuccessful.

Furthermore, the ensuing output from a client like e.g. `mpc` will have the wrong position, which is reset to "0:00":

```
% mpc seek 1:00
somefile.ogg
[playing] #8/12   0:00/4:01 (0%)
volume: 40%   repeat: on    random: off   single: off   consume: off
```

I understand that it's impossible to seek exactly when a file is being streamed, but it is quite possible to request a range via HTTP, and given the total track time, and the sought position, as well as the file length, it's possible to estimate a position.

## Version

```
Music Player Daemon 0.19.21

Copyright (C) 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright (C) 2008-2014 Max Kellermann <max@duempel.org>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


Database plugins:
 simple proxy upnp

Storage plugins:
 local smbclient nfs

Neighbor plugins:
 smbclient upnp

Decoders plugins:
 [mad] mp3 mp2
 [mpg123] mp3
 [vorbis] ogg oga
 [oggflac] ogg oga
 [flac] flac
 [opus] opus ogg oga
 [sndfile] wav aiff aif au snd paf iff svx sf voc w64 pvf xi htk caf sd2
 [audiofile] wav au aiff aif
 [dsdiff] dff
 [dsf] dsf
 [faad] aac
 [mpcdec] mpc
 [wavpack] wv
 [modplug] 669 amf ams dbm dfm dsm far it med mdl mod mtm mt2 okt s3m stm ult umx xm
 [mikmod] amf dsm far gdm imf it med mod mtm s3m stm stx ult uni xm
 [sidplay] sid mus str prg P00
 [wildmidi] mid
 [fluidsynth] mid
 [adplug] amd d00 hsc laa rad raw sa2
 [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tak tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve
 [gme] ay gbs gym hes kss nsf nsfe sap spc vgm vgz
 [pcm]

Output plugins:
 shout null fifo pipe alsa roar ao oss openal pulse jack httpd recorder

Encoder plugins:
 null vorbis opus lame wave flac

Archive plugins:
 [bz2] bz2
 [zzip] zip
 [iso] iso

Input plugins:
 file alsa archive curl ffmpeg smbclient nfs mms cdio_paranoia

Playlist plugins:
 extm3u m3u pls xspf asx rss soundcloud cue embcue

Protocols:
 file:// http:// https:// mms:// mmsh:// mmst:// mmsu:// gopher:// rtp:// rtsp:// rtmp:// rtmpt:// rtmps:// smb:// nfs:// cdda:// alsa://
```

## Log

```
client: [37] opened from [::1]:42760
client: [37] process command "status"
client: [37] command returned 0
client: [37] process command "seekid "46" "120""
playlist: queue song 1:"http://kids.mtvic.madduck.net:80/contents/music/nexttrack.ogg"
client: [37] command returned 0
client: [37] process command list
client: process command "status"
client: command returned 0
client: process command "currentsong"
client: command returned 0
client: [37] process command list returned 0
client: [37] closed
```

**Comment by MaxKellermann** [comment] 2020-04-14 11:13
Your MPD version is very old and unsupported.

**Comment by madduck** [comment] 2020-04-14 11:49
… but this bug also exists in the current version.

**Comment by MaxKellermann** [comment] 2020-04-14 11:57
Then why is this bug report about the old version? I'll reopen your bug report, and then you can add information about the latest version.

**Comment by MaxKellermann** [comment] 2020-04-14 14:13
Duplicate of https://github.com/MusicPlayerDaemon/MPD/issues/811

**Closed** 2020-04-14 14:15 UTC
Labels: duplicate
