### ISSUE TITLE
After update 0.21.17 => 0.21.18 MPD with nfs storage plugin hangs on Songs from cue files 

### ISSUE THREAD

**Issue by TheDonDan** [MusicPlayerDaemon/MPD#756] opened 2020-02-06 09:23 UTC
### Describe the bug

Running Arch Linux with MPD 0.21.18 on an Raspberry Pi Model B Plus Rev 1.2.
MPD on the RPi is configured as satellite accessing the data via an NFS share (storage plugin).

Until version 0.21.17 everything was working fine. After the update from 0.21.17 => 0.21.18 the MPD server has become difficulties with playing songs from cue files. 
Please see "Actual Behavior" . Maybe you have an idea what changed between the two version that could cause such an behavior....I didn't find nothing suspicious...If there are still questions or you need more info, please do not hesitate to ask. Thank you in advance.

## Expected Behavior
Start playing wenn issuing the play command on an Song in the middle of an Album. Audio data is an flac or ape file with the corresponding cue file. 

## Actual Behavior
Gets stuck on 0 seconds wenn issuing the play command on an Song if the audio data is an flac or ape file with the corresponding cue file. Sometimes it is still possible to issue an stop command and afterwards play (suceffuly) other audio data that is not bound to an cue file. 
If trying to play other file without issuing the stop command than MPD hangs and it is needed to kill it with the -KILL switch and restart the service.

After restarting the MPD service everything works fine for a short while, but after waiting ca. 20 min with stoped playback the issue appears again.

## Version

Music Player Daemon 0.21.18 (0.21.18)
Copyright 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2018 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple proxy upnp

Storage plugins:
 local smbclient udisks nfs curl

Neighbor plugins:
 smbclient upnp udisks

Decoders plugins:
 [mad] mp3 mp2
 [mpg123] mp3
 [vorbis] ogg oga
 [oggflac] ogg oga
 [flac] flac
 [opus] opus ogg oga
 [sndfile] wav aiff aif au snd paf iff svx sf voc w64 pvf xi htk caf sd2
 [audiofile] wav au aiff aif
 [dsdiff] dff
 [dsf] dsf
 [hybrid_dsd] m4a
 [faad] aac
 [mpcdec] mpc
 [wavpack] wv
 [modplug] 669 amf ams dbm dfm dsm far it med mdl mod mtm mt2 okt s3m stm ult umx xm
 [mikmod] amf dsm far gdm imf it med mod mtm s3m stm stx ult uni xm
 [wildmidi] mid
 [fluidsynth] mid
 [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 adx afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tak tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve
 [gme] ay gbs gym hes kss nsf nsfe sap spc vgm vgz
 [pcm]

Filters:
 libsamplerate soxr

Tag plugins:
 id3tag

Output plugins:
 shout null fifo pipe alsa ao oss openal solaris pulse jack httpd recorder

Encoder plugins:
 null vorbis opus lame twolame wave flac

Archive plugins:
 [bz2] bz2
 [zzip] zip
 [iso] iso

Input plugins:
 file archive alsa tidal qobuz curl ffmpeg smbclient nfs mms cdio_paranoia

Playlist plugins:
 extm3u m3u pls xspf asx rss soundcloud flac cue embcue

Protocols:
 file:// alsa:// tidal:// qobuz:// http:// https:// gopher:// rtp:// rtsp:// rtmp:// rtmpt:// rtmps:// smb:// nfs:// mms:// mmsh:// mmst:// mmsu:// cdda://

Other features:
 avahi dbus udisks epoll icu inotify ipv6 systemd tcp un

**Comment by MaxKellermann** [comment] 2020-02-16 18:48
This is a surprising problem, because there were no NFS-related changes between those MPD versions, and I have no problem at all with NFS.
Have you upgraded other software at the same time, like libnfs?
Which libnfs version are you using?
Can you confirm that downgrading to MPD 0.21.17 makes the problem disappear?
I need a backtrace of all threads when MPD hangs.

**Comment by anwyn** [comment] 2020-03-26 11:49
Just for confirmation and expansion, I'm also using the nfs plugin as well as the proxy plugin and see mpd hangs after periods of inactivity. It is completely unresponsive. A restart of the mpd user service fixes it, but systemd needs to hard-kill mpd. 

I do not, however, use cue files. 
Output with Jack. 
Database via proxy on the NAS.

```
systemd[5967]: Stopping Music Player Daemon...
systemd[5967]: mpd.service: State 'stop-sigterm' timed out. Killing.
systemd[5967]: mpd.service: Killing process 6293 (mpd) with signal SIGKILL.
```

```
Music Player Daemon 0.21.18 (0.21.18)
Copyright 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2018 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple proxy upnp

Storage plugins:
 local udisks nfs

Neighbor plugins:
 upnp udisks

Decoders plugins:
 [mad] mp3 mp2
 [vorbis] ogg oga
 [oggflac] ogg oga
 [flac] flac
 [sndfile] wav aiff aif au snd paf iff svx sf voc w64 pvf xi htk caf sd2
 [audiofile] wav au aiff aif
 [dsdiff] dff
 [dsf] dsf
 [hybrid_dsd] m4a
 [mpcdec] mpc
 [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 adx afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tak tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve
 [pcm]

Filters:


Tag plugins:
 id3tag

Output plugins:
 shout null fifo pipe alsa openal pulse jack httpd

Encoder plugins:
 null vorbis wave flac

Archive plugins:
 [bz2] bz2
 [zzip] zip

Input plugins:
 file archive alsa curl ffmpeg nfs

Playlist plugins:
 extm3u m3u pls xspf asx rss soundcloud flac cue embcue

Protocols:
 file:// alsa:// http:// https:// gopher:// rtp:// rtsp:// rtmp:// rtmpt:// rtmps:// nfs://

Other features:
 avahi dbus udisks epoll icu inotify ipv6 systemd tcp un

```

**Comment by mxjeff** [comment] 2020-04-16 13:56
The same issue here. Proxied DB and NFS share setup.
Happens with regular flac/mp3 (did not tried cue).

It appeared with 0.21.22 (upgrading from 0.21.17).

Here are conf/version and threads backtrace :
https://gist.github.com/mxjeff/facc06f67834eeee911c5bf06da201e4

**Comment by MaxKellermann** [comment] 2020-04-23 14:22
This bug report is useless.
@TheDonDan never replied to my questions.
@anwyn didn't post any backtrace and didn't answer any of my questions either.
@mxjeff posted a backtrace, but the backtrace shows no hang, no playback, MPD idling around waiting for something to do.
Closing this one.

**Closed by MaxKellermann** 2020-04-23 14:22 UTC
Labels: bug

**Comment by gilphilbert** [comment] 2020-05-26 23:24
I have experienced this as well. I can confirm the backtrace is accurate, MPD produces no log entries during this hang and nothing even in verbose mode, it just freezes until killed.

During playback it works fine, but if left paused or stopped when MPD starts playing again it plays a second or so (presumably whatever is cached) then becomes unresponsive until the service is killed. Subsequent restarts result in the same behavior every time.

**Comment by mxjeff** [comment] 2020-05-27 08:11
@gilphilbert, installing 0.21.23 fixed it for me.  
8ed533a probably addressed the issue.

**Comment by MaxKellermann** [comment] 2020-05-27 11:31
@gilphilbert please write a new bug report if this affects the latest MPD release.
If you don't run the latest version, please do not report any bugs (and don't confirm existing bug reports). Chances are that your bug was already solved.
