### ISSUE TITLE
Play non existent mms stream from existent URL results in freeze

### ISSUE THREAD

**Issue by skidoo23** [MusicPlayerDaemon/MPD#261] opened 2018-04-07 14:34 UTC
MPD 0.20 from git, Debian x64 testing, libmms 0.6.4 from distribution. Compiled with CC=clang-5.0 CXX=clang++-5.0 --enable-mms and --enable-debug

`$ mpc add mms://www.google.com`

Try to play stream results in frozen MPD.

mpd.log
```
Apr 07 15:47 : client: [0] process command "playid "67""
Apr 07 15:47 : playlist: play 66:"mms://www.google.com"
```
(log ends here)

Daemon needs to be killed with -9 option. No debug output with gdb. Please give advice tor debugging.

**Comment by MaxKellermann** [comment] 2018-04-09 17:17
Duplicate of #253?
You said you're using 0.20, but that version was released more than a year ago and doesn't contain the fix for #253. Therefore, from the information you posted, this bug report is bogus.

**Closed by MaxKellermann** 2018-04-09 17:17 UTC

**Comment by skidoo23** [comment] 2018-04-09 20:18
Sorry copy & paste error. MPD is lemonfresh git (master) made clean and does contain fix for #253. Duplicate to #253? Not sure: mmsh://mediau.yle.fi/a_radiosavo works quite well after applying the fix.

**Comment by MaxKellermann** [comment] 2018-04-09 20:29
"Playing" this stream results in `mmsx_connect()` hanging because Google's server discards the SYN packets to port 1755. It hangs until the TCP connect timeout expires, which is 2 minutes by default. This probably means that your patience for MPD to recover was less than these 2 minutes.
Looks like this in strace:
`connect(5, {sa_family=AF_INET, sin_port=htons(1755), sin_addr=inet_addr("216.58.205.68")}, 16) = -1 ETIMEDOUT (Connection timed out) <130.128904>`
Now the thing is that `libmms` exposes only a synchronous API which cannot be cancelled. This means that MPD has no chance but to wait for `libmms` to return, which looked like freezing to you. There is no other way.
Sorry, this is a `libmms` API misdesign, not a MPD bug. Report this to the `libmms` developers. There is nothing I can do for you.

**Comment by skidoo23** [comment] 2018-04-10 17:25
Reported by someone else in late 2015 to libmms developer team. https://sourceforge.net/p/libmms/bugs/21
