### ISSUE TITLE
The 'next' command resets volume even after a setvol to the contrary

### ISSUE THREAD

**Issue by davehayes** [MusicPlayerDaemon/MPD#1055] opened 2021-01-18 23:28 UTC
## Bug report

The 'next' command sets the volume to 45. This number is not configured anywhere, nor can I seem to alter the behavior of 'next' with respect to volume.

### Describe the bug

So if I use 'setvol' I'm telling MPD to stay at that volume. It does for the most part, until I issue a 'next' command. The use case here is that I want to immediately interrupt the current song playing and go to the next one.  

Here is the command flow.  I use a very short and simple perl script to talk to the daemon, which is available on request. I have edited out some of the status info for brevity. 

```
setvol 100
OK
status
volume: 100
...
consume: 1
...
state: play
xfade: 2
...
OK
next
OK
status
volume: 45
...
consume: 1
...
state: play
xfade: 2
...
OK
```

## Expected Behavior

Given the documentation, I would expect that the setvol setting would be preserved across a 'next' command, since it's preserved across a normal song change.

## Actual Behavior

The volume is reset to 45 after each 'next' command

## Desired Behavior

There is a use case I can see where you would want 'next' to reset the volume. Currently there is no MPD way to fade out the currently playing song in the middle of said song and move to the next song. I had planned to do this by simply issuing several setvol commands and then use the 'next' command to consume the current entry and start the next song. So if it was intentional to reset the volume after a 'next' I can see why. :)

If I were coding this, I would add these two configuration constants and make them work:

```
default_vol     This value will be assigned to volume if 'default_vol_on_play' is true and a play or next command is received. 
default_vol_on_play    This boolean controls the assignment of default_vol to volume. If true, the value of 'default_vol' will be assigned to volume on each play or next command. If false, volume will only change via a 'setvol' command
```

Addressing the use case above, you could create a command 'fadenext' which will fade the current song and move to the next song just like next does. That's wishing tho. :D

## Version

```
Music Player Daemon 0.21.26 (0.21.26)
Copyright 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2018 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple

Storage plugins:
 local


Decoders plugins:
 [vorbis] ogg oga
 [oggflac] ogg oga
 [flac] flac
 [sndfile] wav aiff aif au snd paf iff svx sf voc w64 pvf xi htk caf sd2
 [dsdiff] dff
 [dsf] dsf
 [hybrid_dsd] m4a
 [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 adx afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tak tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve
 [pcm]

Filters:


Tag plugins:
 id3tag

Output plugins:
 null fifo pipe oss httpd recorder

Encoder plugins:
 null vorbis wave flac

Archive plugins:
 [bz2] bz2

Input plugins:
 file archive curl ffmpeg

Playlist plugins:
 extm3u m3u pls xspf asx rss flac cue embcue

Protocols:
 file:// http:// https:// gopher:// hls+http:// hls+https:// rtp:// rtmp:// rtmpt:// rtmps://

Other features:
 icu ipv6 tcp un
```

## Log

I didn't see anything relevant here. I'm testing MPD at the moment and I'm willing to turn on --verbose if you think it will help.

**Comment by MaxKellermann** [comment] 2021-01-20 13:48
Your MPD version is old and unsupported.
What is your output/mixer configuration?

**Comment by davehayes** [comment] 2021-01-20 23:31
This is my testing setup. 

```
audio_output {
	type		"oss"
	name		"My OSS Device"
#	device		"/dev/dsp"	# optional
#	mixer_type      "hardware"	# optional
#	mixer_device	"/dev/mixer"	# optional
#	mixer_control	"PCM"		# optional
}
```

**Comment by MaxKellermann** [comment] 2021-01-21 06:00
Do you have a global mixer_type setting?

**Comment by davehayes** [comment] 2021-01-21 17:54
No.

**Comment by MaxKellermann** [comment] 2021-01-21 18:35
Is there something like strace on FreeBSD? It would be useful to see when and how MPD opens the OSS mixer device, and whether/why MPD changes the volume settings on song change.

**Comment by davehayes** [comment] 2021-01-21 20:10
I do have a ktrace of the issue if you would like to see it. It seems that the first `play` command -also- triggers the reduction to 45. However this might not be needed. In doing all this digging, I found some more smoking guns that may help the resolution of this. Note the following:

```
> sysctl hw.snd.default_unit
hw.snd.default_unit: 4
> ls -l /dev/dsp4 /dev/dsp
crw-rw-rw-  1 root  wheel  0xcb Jan 21 11:44 /dev/dsp
crw-rw-rw-  1 root  wheel  0xcb Jan 21 11:44 /dev/dsp4
> ls -l /dev/mixer4 /dev/mixer
crw-rw-rw-  1 root  wheel  0x8a Dec 26 05:26 /dev/mixer
crw-rw-rw-  1 root  wheel  0x8a Dec 26 05:26 /dev/mixer4
> mixer -f /dev/dsp
Mixer pcm      is currently set to  45:45
Mixer rec      is currently set to  45:45
> mixer -f /dev/mixer
Mixer vol      is currently set to 100:100
Mixer pcm      is currently set to 100:100
Mixer speaker  is currently set to  74:74
Mixer line     is currently set to   1:1
Mixer mic      is currently set to  67:67
Mixer mix      is currently set to  74:74
Mixer rec      is currently set to  37:37
Mixer igain    is currently set to   0:0
Mixer ogain    is currently set to 100:100
Recording source: mic
```

At least now I know where the 45 comes from. It seems that there are two different mixer settings, depending on what device you are pointed at and [this forum post](https://forums.freebsd.org/threads/mixer-cant-change-volume.60633/) (I can duplicate this poster's behavior here) suggests to me that any volume operations (read or write) should use /dev/mixer rather than /dev/dsp. 

Is this behavior possible to configure or would this require a code change?

**Comment by MaxKellermann** [comment] 2021-01-21 20:22
I don't quite understand. What behavior do you want to configure?

**Comment by davehayes** [comment] 2021-01-21 20:23
So, for example, if I send a "setvol 100" command, I would expect "play" to leave the volume at 100. If I send a "next" command, I would expect the volume not to change.

**Comment by MaxKellermann** [comment] 2021-01-21 20:27
I think we misunderstand. My point is: MPD doesn't change the volume when you start or stop playback or if you change songs.
You say it does, and I say if it does, it's a bug. Now it's up to you to provide data (e.g. the ktrace) so we can find out why the volume changes, and whether it's really MPD's fault.
Your previous post said MPD should use /dev/mixer instead of /dev/dsp to set the volume, but that's what MPD already does, so I'm confused why you post it. Does your ktrace show that MPD uses /dev/dsp?

**Comment by davehayes** [comment] 2021-01-21 20:51
Actually, I claim MPD actually _does_ change the volume. Here's my evidence:

```
> ktrace -i musicpd stationmpdtest.conf
Jan 21 12:33 : exception: Failed to access /MightyDJ/mpd/playlists: No such file or directory
Jan 21 12:33 : vorbis: Xiph.Org libVorbis 1.3.7
Jan 21 12:33 : sndfile: libsndfile-1.0.30
Jan 21 12:33 : hybrid_dsd: The Hybrid DSD decoder is disabled because it was not explicitly enabled
Jan 21 12:33 : exception: Failed to access /MightyDJ/mpd/music: No such file or directory
Jan 21 12:33 : exception: Failed to open '/MightyDJ/mpd/database': No such file or directory
Jan 21 12:33 : curl: version 7.72.0
Jan 21 12:33 : curl: with LibreSSL/3.1.5
> mpdtalk ./mpdsocket
OK MPD 0.21.11
status
volume: 100
repeat: 0
random: 0
single: 0
consume: 0
playlist: 1
playlistlength: 0
mixrampdb: 0.000000
state: stop
OK
setvol 100
OK
addid "/MDJStorage/05/d7/0aea.flac"
Id: 1
OK
play
OK
status
volume: 45
repeat: 0
random: 0
single: 0
consume: 0
playlist: 2
playlistlength: 1
mixrampdb: 0.000000
state: play
song: 0
songid: 1
time: 2:282
elapsed: 1.753
bitrate: 1268
duration: 282.354
audio: 44100:24:2
OK
setvol 100
OK
```
That last `setvol` I have verified increases the volume of playback. 

I have put the ktrace file up for perusal at [this link](https://www.jetcafe.org/dave/mpddump.txt)  I can verify it opens both `/dev/dsp` and `/dev/mixer` but what it actually does with those is still a mystery to me.

**Comment by MaxKellermann** [comment] 2021-01-21 21:12
Your ktrace proves that:
- MPD opens `/dev/dsp` for submitting PCM data, but never does any mixer ioctl
- MPD opens `/dev/mixer`, and there are exactly two `SOUND_MIXER_WRITE` calls: one for each `setvol 100` command from your client, but never at start of end of playback

So whatever changes your mixer volume, it's certainly not MPD!

**Comment by davehayes** [comment] 2021-01-21 21:31
Can you explain this conclusion? I cannot verify your statements by seeing any evidence of `SOUND_MIXER_WRITE`. I see an `ioctl` of `MOUSE_GETLEVEL` on the filehandle that I think you opened to `/dev/mixer`.

**Comment by MaxKellermann** [comment] 2021-01-21 21:35
All operations on `/dev/dsp`:
```
 61628 musicpd  CALL  fstatat(AT_FDCWD,0x21007a,0x7fffffffc430,0)
 61628 musicpd  NAMI  "/dev/dsp"
 61628 musicpd  STRU  struct stat {dev=1895890688, ino=123, mode=020666, nlink=1, uid=0, gid=0, rdev=123, atime=1611261221.053204000, mtime=1611261221.053204000, ctime=1611261221.053204000, birthtime=-1, size=0, blksize=4096, blocks=0, flags=0x0 }
 61628 output:My OSS D CALL  openat(AT_FDCWD,0x21007a,0x108001<O_WRONLY|O_NOCTTY|O_CLOEXEC>)
 61628 output:My OSS D NAMI  "/dev/dsp"
 61628 output:My OSS D RET   openat 17/0x11
 61628 output:My OSS D CALL  ioctl(0x11,SOUND_PCM_WRITE_CHANNELS,0x7fffdf5f739c)
 61628 output:My OSS D CALL  ioctl(0x11,SNDCTL_DSP_SPEED,0x7fffdf5f739c)
 61628 output:My OSS D CALL  ioctl(0x11,SNDCTL_DSP_SETFMT,0x7fffdf5f739c)
 61628 output:My OSS D CALL  write(0x11,0x807ab6000,0xfb0)
[... lots of writes ...]
 61628 output:My OSS D CALL  ioctl(0x11,SNDCTL_DSP_HALT,0)
 61628 output:My OSS D CALL  close(0x11)
```
All operations on `/dev/mixer`:
```
 61628 musicpd  CALL  openat(AT_FDCWD,0x20aa35,0x108000<O_RDONLY|O_NOCTTY|O_CLOEXEC>)
 61628 musicpd  NAMI  "/dev/mixer"
 61628 musicpd  RET   openat 15/0xf
 61628 musicpd  CALL  ioctl(0xf,MOUSE_GETLEVEL,0x7fffffffca04)
 61628 musicpd  CALL  ioctl(0xf,0xc0044d04,0x7fffffffcaac)
 61628 musicpd  CALL  ioctl(0xf,MOUSE_GETLEVEL,0x7fffffffca04)
 61628 musicpd  CALL  ioctl(0xf,0xc0044d04,0x7fffffffcaac)
 61628 musicpd  CALL  close(0xf)
```
`MOUSE_GETLEVEL` is really `SOUND_MIXER_READ_PCM` (both numeric values are the same, and ktrace doesn't know which kind of device this is).
`0xc0044d04` is `SOUND_MIXER_WRITE_PCM`, and both of these calls are right after the `setvol 100` commands from your MPD client.

**Comment by davehayes** [comment] 2021-01-21 21:56
Thank you for that, I really need to track this down and I appreciate your scientific approach. :)

I note the 2nd status command did some threaded mutex operations in between the receiving of the command and the printing of the 45 volume. The first one did not. Could that have an outside possibility of changing the volume? 

The only process that has `/dev/mixer` open is the xfce4 audio mixer and that is set to 100.

**Comment by MaxKellermann** [comment] 2021-01-22 06:17
> Could that have an outside possibility of changing the volume?

No. I pasted an exhaustive list of system calls affecting your dsp/mixer device. No matter how much thread synchronization or other complicated stuff is being done - if it's not `ioctl`, it won't affect the mixer volume.

**Comment by MaxKellermann** [comment] 2021-01-22 07:29
Closing, because all data suggests that this is not caused by MPD's actions.

**Closed by MaxKellermann** 2021-01-22 07:29 UTC
Labels: bogus

**Comment by davehayes** [comment] 2021-02-05 00:56
For those googling who find this, I found the issue. Indeed it was not MPD. There are two things in FreeBSD that must be done. Here is my [source for the sysctl information.](https://forums.freebsd.org/threads/sound-hw-snd-vpc_0db-trying-to-understand.66102/)

First, there are two sysctl settings which represent an "autoreset" of the volume of the sound system:

```
hw.snd.vpc_0db: 0db relative level
hw.snd.vpc_autoreset: automatically reset channels volume to 0db
```
If I understand these correctly, the system clamps the audio volume to the `0db` value upon initiating a play request. So I set the `0db` value to 100 and `autoreset` to 0. 

Next, and this was not really obvious, I had to become `root`, and find the actual audio device, which is not `/dev/dsp`. It seems `/dev/dsp` is some kind of alias to the actual device you are using for output which only shows up when you actually access it (invisble to an `ls` of your devfs directory).  Thus, I had to do this to introspect the sound system:

```
> cat /dev/sndstat
Installed devices:
pcm0: <NVIDIA (0x0099) (HDMI/DP 8ch)> (play)
pcm1: <NVIDIA (0x0099) (HDMI/DP 8ch)> (play)
pcm2: <NVIDIA (0x0099) (HDMI/DP 8ch)> (play)
pcm3: <NVIDIA (0x0099) (HDMI/DP 8ch)> (play)
pcm4: <Realtek ALC1220 (Rear Analog 5.1/2.0)> (play/rec) default
pcm5: <Realtek ALC1220 (Front Analog)> (play/rec)
pcm6: <Realtek ALC1220 (Rear Digital)> (play)
No devices installed from userspace.
```
In my case I needed to know that I was using pcm4, thus implying the mixer device I needed was `/dev/dsp4`. So as `root` I needed to set  `/dev/dsp4` to be 100:

```
# mixer -f /dev/dsp4 pcm 100:100
```

After performing both settings described above, mpd will now not reset the volume on a `next` or `play`. 

Apologies to MaxKellerman for wasting his time with this.
