### ISSUE TITLE
'add' command works via unix socket and doesn't work via network

### ISSUE THREAD

**Issue by RomanBurunkov** [MusicPlayerDaemon/MPD#1022] opened 2020-12-08 21:44 UTC
## Question

Hi there,

I've faced with an issue of Access denied error while trying to add songs from a fs to the mpd queue.

OS: Ubuntu 18.04
`mpd --version` : `v0.22.3`

Works just fine: `mpc add file:///home/roman/music/c09091f1-2aec-4df3-9839-66987a281834.mp3`
Doesn't work: `mpc --host 127.0.0.1 --port 6600 add file:///home/roman/music/c09091f1-2aec-4df3-9839-66987a281834.mp3`

The error I'm facing is `error adding file... Access denied`

I've tried to debug and compile modified version what help's me to identify which condition affect adding song via network.

It is from `File.cxx` lines 38-40

```
	if (uid < 0)
		/* unauthenticated client */
		throw ProtocolError(ACK_ERROR_PERMISSION, "Access denied");
```

I also tried to use other clients and got the same error.

One more thing I've mention that in Ubuntu add command could not work(even via unix socket) right after you've installed mpd with the same Access denied error. And via unix socket it starts to work after rebooting the system, probably there is something related to the mpd startup script for this distributive.

Is there any means to get add command works from the local network connection? I haven't found any in docs and internet...

**Comment by MaxKellermann** [comment] 2020-12-08 21:54
This works as designed, but unfortunately, the documentation isn't clear enough about it. Local socket connections and its special privileges are mentioned, but not below the "add" documentation.
(Don't call it "local network connection", you may mix it up with "local sockets", which is the vendor neutral name for "unix domain sockets". What you mean is "loopback connection".)

The reason for the distinction is that only for local sockets, MPD can verify information about the client process. This is not possible with loopback.

**Comment by RomanBurunkov** [comment] 2020-12-08 22:31
Hi @MaxKellermann 

Thank you for clarification.

Does that mean that it is not possible to add songs to queue with 'add' command from a network connection?
I've tried to use a real address instead of 127.0.0.1, by changing bind_to_address in config and got the same error:

`mpc --host 10.255.0.111 --port 6600 add file:///home/roman/music/c09091f1-2aec-4df3-9839-66987a281834.mp3`

If so is there other options to do that?

**Comment by MaxKellermann** [comment] 2020-12-09 06:31
By default configuration, all clients can add songs to the queue. But only "local" clients can add arbitrary local files; all other clients can only add songs from the `music_directory` or remote files.
The idea behind this is that arbitrary file access to arbitrary remote clients can be dangerous, and so MPD wants to allow this only to clients which would have access to those files anyway; and that can be only be checked for "local" clients.

**Comment by RomanBurunkov** [comment] 2020-12-09 06:53
I see.

Thank you for that details.
Them wasn't obvious for me.

**Comment by MaxKellermann** [comment] 2020-12-09 08:20
I'll reopen it, and close it with a commit which improves the documentation. This is a documentation issue.

**Closed** 2021-02-15 21:52 UTC

**Comment by W1zzardTPU** [comment] 2022-05-16 22:18
I'm trying to control a locally running MPD on Raspberry through C# using Simple.MPD (https://www.nuget.org/packages/Simple.MPD/).

Simple.MPD only supports connecting over TCP (not socket).

If I understand Max's explanation correctly there is no way to add an arbitrary file in this setup?

Any way to get a config option to ignore the uid check?
