### ISSUE TITLE
Segfaults in id3 decoding with MADDecoderPlugin

### ISSUE THREAD

**Issue by KungFuJesus** [MusicPlayerDaemon/MPD#1463] opened 2022-02-25 21:16 UTC
### Describe the bug
Updating to mpd 0.16.1 somehow made my database inaccessible (some complaint about tags).  I renamed it and tried to regenerate it.  I was greeted with a segfault parsing an id3tag in mad decoder.  What's weird is that it seems that this should be happening for everybody using this, as this line here:
https://github.com/MusicPlayerDaemon/MPD/blob/v0.23.x/src/decoder/plugins/MadDecoderPlugin.cxx#L975

Explicitly passes a null pointer to this function:
https://github.com/tenacityteam/libid3tag/blob/0.16.1/ucs4.c#L38

Which me immediately tries to dereference it.  

## Expected Behavior
No segfault.

## Actual Behavior
Segfault.

## Version

```
Music Player Daemon 0.23.5 (0.23.5)
Copyright 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2021 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple proxy

Storage plugins:
 local smbclient udisks

Neighbor plugins:
 smbclient udisks

Decoders plugins:
 [mad] mp3 mp2
 [mpg123] mp3
 [vorbis] ogg oga
 [oggflac] ogg oga
 [flac] flac
 [opus] opus ogg oga
 [audiofile] wav au aiff aif
 [dsdiff] dff
 [dsf] dsf
 [hybrid_dsd] m4a
 [mpcdec] mpc
 [mikmod] amf dsm far gdm imf it med mod mtm s3m stm stx ult uni xm
 [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 adx afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tak tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve rtp:// rtsp:// rtsps://
 [pcm]

Filters:
 libsamplerate

Tag plugins:
 id3tag

Output plugins:
 shout null fifo alsa oss openal jack httpd

Encoder plugins:
 null vorbis opus wave flac

Archive plugins:
 [bz2] bz2
 [zzip] zip

Input plugins:
 file io_uring archive alsa curl ffmpeg smbclient mms

Playlist plugins:
 extm3u m3u pls xspf asx rss flac cue embcue

Protocols:
 file:// alsa:// ftp:// ftps:// gopher:// hls+http:// hls+https:// http:// https:// mms:// mmsh:// mmst:// mmsu:// rtmp:// rtmpe:// rtmps:// rtmpt:// rtmpte:// rtmpts:// rtp:// rtsp:// rtsps:// smb:// srtp://

Other features:
 dbus udisks epoll icu inotify ipv6 tcp un
```

## Log

```
mad: encoder delay is 576, encoder padding is 1908
update: added E/Electric Light Orchestra/1997 - Light Years The very Best 1997/CD1/17-Electric Light Orchestra - Don't Walk Away.mp3
update: reading E/Electric Light Orchestra/1997 - Light Years The very Best 1997/CD1/18-Electric Light Orchestra - Don't Bring Me Down.mp3

Thread 4 "update" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe9d00640 (LWP 21975)]
id3_ucs4_length (ucs4=ucs4@entry=0x0) at /var/tmp/portage/media-libs/libid3tag-0.16.1-r1/work/libid3tag-0.16.1/ucs4.c:42
42	/var/tmp/portage/media-libs/libid3tag-0.16.1-r1/work/libid3tag-0.16.1/ucs4.c: No such file or directory.
(gdb) p ucs4
$1 = (const id3_ucs4_t *) 0x0
```

**Comment by MaxKellermann** [comment] 2022-02-25 22:03
Duplicate of https://github.com/MusicPlayerDaemon/MPD/issues/1460

**Closed by MaxKellermann** 2022-02-25 22:03 UTC
