### ISSUE TITLE
albumart file template configuration option

### ISSUE THREAD

**Issue by Forage** [MusicPlayerDaemon/MPD#710] opened 2020-01-14 14:35 UTC
## Feature request
`albumart` searches for a `cover.*` file in the same folder as the music file.
It would be great if a configuration option could be added to provide a template used to search for the file.
This would allow to search in a different folder and/or for different file names.
In some cases for example folder.jpg or front.jpg tends to be the de facto standard.
Myself I put the cover art in a subfolder as well.

Even better would be to be able to provide multiple option, by either repeating the config option or providing something like a character separated list in one and the same value. This way you can cover the multiple situations like:

- `artwork/front.*`
- `cover.*`
- `../covers/front.*`

**Comment by MaxKellermann** [comment] 2020-01-18 22:38
Duplicate of https://github.com/MusicPlayerDaemon/MPD/issues/301

**Closed by MaxKellermann** 2020-01-18 22:38 UTC
Labels: feature
