### ISSUE TITLE
Windows builds

### ISSUE THREAD

**Issue by dimqua** [MusicPlayerDaemon/MPD#71] opened 2017-06-27 00:32 UTC
Please update mpd's Windows build to the latest version. Thanks

**Comment by guizhenwei** [comment] 2017-07-03 16:11
I've just follow the documentation to build a Windows 32bit executable on Debian 9. (By issuing command: `./win32/build.py --32`)

I git pull the latest version of MPD(on commit: 6e2b34875872a13d6b28f2eb8c7cacefa641f4bd).

And after compiling, it produced a 90+M size `mpd.exe` binary. (I think the size is way too large)

I then try to connect to this new version of MPD daemon on my Windows 10 PC, and i found strange problems:

Some commands work(like: `mpc stats`), but all the queries to database file like `mpc ls` `mpc update` `mpc listall` ... crashed the daemon. Which means the binary i build is not usable.

At the end, i found the database file was generated in binary mode, the content in the database file is not human readable, it's all binary.

I guess this is the issues for the crashes. Hope can fix.

@MaxKellermann

**Comment by MaxKellermann** [comment] 2017-07-03 16:16
Deleted text from @guizhenwei because he was spamming this issue with a bug report that is off-topic here and is a duplicate of #52

**Comment by sss123next** [comment] 2017-08-01 21:29
http://sss.chaoslab.ru/mpd32.exe  md5sum 8ab5150ef46e5dae7ffa5dcb688ebbbe
http://sss.chaoslab.ru/mpd64.exe md5sum 801d6f1652b3b4357beea6e8026e9297

with sse2 cpu, curl,ffmpeg,vorbis,src,soxr,flac,lame,soundcloud,expat, database,httpd
without: icu,twolame, musepack, wavpack. openal sqlite iso9660 cdio-paranoia mpg123 bzip2 shout, shine
stripped, upx compressed

you can send me btc ;)

**Comment by MaxKellermann** [comment] 2017-08-02 22:40
Deleted comment because he was begging for bitcoins. This is not the place to make money.

**Comment by sss123next** [comment] 2017-08-02 22:46
oh, what a pity.
it's very sad for you what you can't understand jokes.
but anyway do as you wish

**Comment by webknjaz** [comment] 2017-08-11 15:24
Let me recommend you adding AppVeyor CI: https://www.appveyor.com/

**Comment by handsomegui** [comment] 2017-09-01 17:39
It would be nice to have 32bit build for Windows platform as well. (Currently its 64bit only)

**Comment by webknjaz** [comment] 2017-09-01 17:59
I believe, you can build x86 under AppVeyor as well.

**Comment by sss123next** [comment] 2017-09-02 05:05
i can do it, but i am afraid deer @MaxKellermann  with world's greatest sense of humor will delete my post again, so i rather not ), feel free to contact me if you need it.
i can build this configuration:
```

########### MPD CONFIGURATION ############

Archive support:
	(-bzip2) (-ISO9660) (-ZIP) 
Client support:
	(+IPv6) (+TCP) (-UNIX Domain Sockets) 
Storage support:
	(-NFS) (-SMB) 
File format support:
	(+AAC) (-AdPlug) (+DSD) (-C64 SID) (+FFMPEG) (+FLAC) (-FluidSynth) (-GME) 
	(+libsndfile) (-MikMod) (-MODPLUG) (-MAD) (-MPG123) (-Musepack) 
	(+Opus) (-OggTremor) (+OggVorbis) (-WAVE) (-WavPack) (-WildMidi) 
Other features:
	(+libsamplerate) (+libsoxr) (-libmpdclient) (-inotify) (-SQLite) 
Metadata support:
	(+ID3) 
Playback support:
	(-ALSA) (-FIFO) (-SNDIO) (+File Recorder) (-Haiku) (+HTTP Daemon) (-JACK) 
	(-libao) (-OSS) (+OpenAL) (-OS X) (-Pipeline) 
	(-PulseAudio) (-ROAR) (-SHOUTcast) (-Solaris) (+WinMM) 
Streaming encoder support:
	(+FLAC) (+LAME) (-Shine) (+Ogg Vorbis) (+Opus) (-TwoLAME) (+WAVE) 
Streaming support:
	(-CDIO_PARANOIA) (+CURL) (-SMBCLIENT) (+Soundcloud) 
	(-MMS) 
Event loop:
	winselect

##########################################


```

**Comment by MaxKellermann** [comment] 2017-09-15 21:46
There are current MPD builds now.

**Closed by MaxKellermann** 2017-09-15 21:46 UTC
Labels: windows
