### ISSUE TITLE
Empty metadata 

### ISSUE THREAD

**Issue by DavidHenryThoreau** [MusicPlayerDaemon/MPD#1091] opened 2021-02-16 17:11 UTC
Since mpd version : 0.22.5, mpc (0.33) can't return metadata :

This mp3 is tagged :
`mediainfo Randy_Granger/A_Place_Called_Peace/03_Chaco_Moon_Meditation.mp3
General                                                                                                                
Complete name                            : Randy_Granger/A_Place_Called_Peace/03_Chaco_Moon_Meditation.mp3
Format                                   : MPEG Audio
File size                                : 5.79 MiB
Duration                                 : 4 min 59 s
Overall bit rate mode                    : Variable  
Overall bit rate                         : 161 kb/s
Album                                    : A Place Called Peace 
Album/Performer                          : Randy Granger
Part/Position                            : 1             
Part/Total                               : 1        
Track name                               : Chaco Moon Meditation                       
Track name/Position                      : 3
Track name/Total                         : 8
Performer                                : Randy Granger
Performer/Sorted by                      : Granger, Randy
Performer/Url                            : http://www.jamendo.com/en/artist/Randy_Granger
Encoded by                               : Jamendo : http://www.jamendo.com | LAME
Thanks to                                : arranger
Publisher                                : Jamendo
Genre                                    : Ambient
Released date                            : 2010
Original/Released date                   : 2010
Recorded date                            : 2010`

Play that song :
`mpc play
Randy_Granger/A_Place_Called_Peace/02_The_Dog_Star.mp3
[playing] #2/6   0:00/0:00 (0%)
volume:100%   repeat: on    random: off   single: off   consume: off`

Get some infos by using mpc (artist, date, track) :
`mpc current -f "%artist% - %title% (%date%)" `

results :
`-  ()`

**Comment by MaxKellermann** [comment] 2021-02-16 18:02
Duplicate of https://github.com/MusicPlayerDaemon/MPD/issues/1089

**Closed by MaxKellermann** 2021-02-16 18:02 UTC
