### ISSUE TITLE
Permissions given by password config file parameter disregarded in 0.23

### ISSUE THREAD

**Issue by PiotrC1** [MusicPlayerDaemon/MPD#1293] opened 2021-10-18 22:27 UTC
In my config file there is a password command:
`password "1234@read,add,control,admin"`
Up to version 0.23.0 mpd was running smoothly with this config. After upgrade to 0.23.0 issuing following commands to mpd via telnet connected to localhost:6600 fail:
`password 1234`
`OK`
`status`
`ACK [4@0] {status} you don't have permission for "status"`
After commenting out `password` I'm able to read status without password.

**Comment by MaxKellermann** [comment] 2021-10-19 07:00
Duplicate of https://github.com/MusicPlayerDaemon/MPD/issues/1282 which is fixed already - 0.23.1 will be out very soon.

**Closed as completed by MaxKellermann** 2021-10-19 07:00 UTC
