### ISSUE TITLE
AIFF tags not being read

### ISSUE THREAD

**Issue by moodeaudio** [MusicPlayerDaemon/MPD#98] opened 2017-08-18 15:17 UTC
Hi,

I'm not able to get Album or Artist tags read from aiff files using MPD 0.20.9. I don't recall this happening in 0.19.19 so maybe a regression?

I have several sets of sample files, the most recent can be downloaded at the link below.

-Tim 

SAMPLE FILES
============
http://moodeaudio.org/files/mike_aiff_test.zip

OS PLATFORM INFO
================
Raspbian Jessie Lite 2017-07-05
Linux kernel 4.9.41-v7+

MPD INFO
================
pi@rp3:~ $ mpd -V
Music Player Daemon 0.20.9

Copyright (C) 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2017 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple proxy

Storage plugins:
 local

Decoders plugins:
 [mad] mp3 mp2
 [mpg123] mp3
 [vorbis] ogg oga
 [oggflac] ogg oga
 [flac] flac
 [dsdiff] dff
 [dsf] dsf
 [faad] aac
 [wavpack] wv
 [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 adx afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tak tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve
 [pcm]

Filters:
 soxr

Tag plugins:
 id3tag

Output plugins:
 shout null fifo pipe alsa httpd recorder

Encoder plugins:
 null vorbis lame wave flac

Archive plugins:
 [iso] iso

Input plugins:
 file alsa archive curl ffmpeg cdio_paranoia

Playlist plugins:
 extm3u m3u pls soundcloud flac cue embcue

Protocols:
 file:// http:// https:// gopher:// rtp:// rtsp:// rtmp:// rtmpt:// rtmps:// cdda:// alsa://

Other features:
 avahi epoll icu inotify systemd tcp un

COMPILE INFO
============
sudo apt-get install libmad0-dev libmpg123-dev libid3tag0-dev \
libflac-dev libvorbis-dev libfaad-dev \
libwavpack-dev \
libavcodec-dev libavformat-dev \
libmp3lame-dev \
libsoxr-dev \
libcdio-paranoia-dev libiso9660-dev \
libcurl4-gnutls-dev \
libasound2-dev \
libshout3-dev libyajl-dev \
libmpdclient-dev \
libavahi-client-dev \
libsystemd-daemon-dev libwrap0-dev \
libboost-dev \
libicu-dev \
libglib2.0-dev

sudo wget http://www.musicpd.org/download/mpd/0.20/mpd-0.20.9.tar.xz
sudo tar xf mpd-0.20.9.tar.xz
cd mpd-0.20.9
sudo sh autogen.sh

sudo ./configure --enable-database --enable-libmpdclient --enable-alsa \
--enable-curl --enable-dsd --enable-ffmpeg --enable-flac \
--enable-id3 --enable-soundcloud --enable-lame-encoder --enable-mad \
--enable-mpg123 --enable-pipe-output --enable-recorder-output --enable-shout \
--enable-vorbis --enable-wave-encoder --enable-wavpack --enable-httpd-output \
--enable-soxr --with-zeroconf=avahi \
--disable-bzip2 --disable-zzip --disable-fluidsynth --disable-gme \
--disable-wildmidi --disable-sqlite --disable-jack --disable-ao --disable-oss \
--disable-ipv6 --disable-pulse --disable-nfs --disable-smbclient \
--disable-upnp --disable-expat --disable-lsr \
--disable-sndfile --disable-audiofile --disable-sidplay

FFMPEG INFO
===========

pi@rp3:~ $ avconv -version
avconv version 11.9-6:11.9-1~deb8u1+rpi1, Copyright (c) 2000-2017 the Libav developers
  built on Apr 26 2017 06:57:28 with gcc 4.9.2 (Raspbian 4.9.2-10)
avconv 11.9-6:11.9-1~deb8u1+rpi1
libavutil     54.  3. 0 / 54.  3. 0
libavcodec    56.  1. 0 / 56.  1. 0
libavformat   56.  1. 0 / 56.  1. 0
libavdevice   55.  0. 0 / 55.  0. 0
libavfilter    5.  0. 0 /  5.  0. 0
libavresample  2.  1. 0 /  2.  1. 0
libswscale     3.  0. 0 /  3.  0. 0

pi@rp3:~ $ dpkg -l | grep libav
ii  libav-tools                    6:11.9-1~deb8u1+rpi1               armhf        Multimedia player, encoder and transcoder
ii  libavcodec-dev                 6:11.9-1~deb8u1+rpi1               armhf        Development files for libavcodec
ii  libavcodec56:armhf             6:11.9-1~deb8u1+rpi1               armhf        Libav codec library
ii  libavdevice55:armhf            6:11.9-1~deb8u1+rpi1               armhf        Libav device handling library
ii  libavfilter5:armhf             6:11.9-1~deb8u1+rpi1               armhf        Libav video filtering library
ii  libavformat-dev                6:11.9-1~deb8u1+rpi1               armhf        Development files for libavformat
ii  libavformat56:armhf            6:11.9-1~deb8u1+rpi1               armhf        Libav file format library
ii  libavresample-dev              6:11.9-1~deb8u1+rpi1               armhf        Development files for libavresample
ii  libavresample2:armhf           6:11.9-1~deb8u1+rpi1               armhf        Libav audio resampling library
ii  libavutil-dev                  6:11.9-1~deb8u1+rpi1               armhf        Development files for libavutil
ii  libavutil54:armhf              6:11.9-1~deb8u1+rpi1               armhf        Libav utility library

LOG OUTPUT
==========
pi@rp3:~ $ tail -f /var/log/mpd/mpd.log 
Aug 17 10:17 : client: [59] opened from 127.0.0.1:49044
Aug 17 10:17 : client: [60] opened from 127.0.0.1:49048
Aug 17 10:17 : client: [60] process command "rescan"
Aug 17 10:17 : update: spawned thread for update job id 4
Aug 17 10:17 : update: starting
Aug 17 10:17 : client: [60] command returned 0
Aug 17 10:17 : client: [60] closed
Aug 17 10:17 : update: updating SDCARD/Stereo Test/LRMonoPhase4.flac
Aug 17 10:17 : client: [53] process command "status"
Aug 17 10:17 : client: [53] command returned 0
Aug 17 10:17 : client: [58] process command "status"
Aug 17 10:17 : client: [58] command returned 0
Aug 17 10:17 : update: recursive directory found
Aug 17 10:17 : client: [53] process command "currentsong"
Aug 17 10:17 : client: [53] command returned 0
Aug 17 10:17 : client: [58] process command "currentsong"
Aug 17 10:17 : client: [58] command returned 0
Aug 17 10:17 : client: [53] process command "close"
Aug 17 10:17 : client: [53] command returned 3
Aug 17 10:17 : client: [53] closed
Aug 17 10:17 : client: [58] process command "close"
Aug 17 10:17 : client: [58] command returned 3
Aug 17 10:17 : client: [58] closed
Aug 17 10:17 : update: updating USB/EXFAT-128GB/Test_music/zippers/08 Ain't Gonna Rain Anymore.aif
Aug 17 10:17 : ffmpeg/aiff: max_analyze_duration 5000000 reached
Aug 17 10:17 : update: updating USB/EXFAT-128GB/Test_music/zippers/08 Pedestal.aif
Aug 17 10:17 : ffmpeg/aiff: max_analyze_duration 5000000 reached
Aug 17 10:17 : update: updating USB/EXFAT-128GB/Test_music/zippers/11 It's Your Problem.aif
Aug 17 10:17 : ffmpeg/aiff: max_analyze_duration 5000000 reached
Aug 17 10:17 : simple_db: removing empty directories from DB
Aug 17 10:17 : simple_db: sorting DB
Aug 17 10:17 : simple_db: writing DB
Aug 17 10:17 : update: finished
Aug 17 10:17 : client: [62] opened from 127.0.0.1:49056
Aug 17 10:17 : client: [62] process command "status"
Aug 17 10:17 : client: [62] command returned 0
Aug 17 10:17 : client: [62] process command "currentsong"
Aug 17 10:17 : client: [62] command returned 0
Aug 17 10:17 : client: [62] process command "close"
Aug 17 10:17 : client: [62] command returned 3
Aug 17 10:17 : client: [62] closed
Aug 17 10:17 : client: [63] opened from 127.0.0.1:49060
Aug 17 10:17 : client: [63] process command "close"
Aug 17 10:17 : client: [63] command returned 3
Aug 17 10:17 : client: [63] closed
Aug 17 10:17 : client: [64] opened from 127.0.0.1:49064
Aug 17 10:17 : client: [65] opened from 127.0.0.1:49068
Aug 17 10:17 : client: [65] process command "status"
Aug 17 10:17 : client: [65] command returned 0
Aug 17 10:17 : client: [65] process command "idle"
Aug 17 10:17 : client: [65] command returned 1
Aug 17 10:17 : client: [64] process command "playlistinfo"
Aug 17 10:17 : client: [64] command returned 0
Aug 17 10:17 : client: [64] process command "close"
Aug 17 10:17 : client: [64] command returned 3
Aug 17 10:17 : client: [64] closed
Aug 17 10:18 : client: [66] opened from 127.0.0.1:49072
Aug 17 10:18 : client: [66] process command "close"
Aug 17 10:18 : client: [66] command returned 3
Aug 17 10:18 : client: [66] closed
Aug 17 10:18 : client: [67] opened from 127.0.0.1:49076
Aug 17 10:18 : client: [67] process command "close"
Aug 17 10:18 : client: [67] command returned 3
Aug 17 10:18 : client: [67] closed
Aug 17 10:18 : client: [68] opened from 127.0.0.1:49080
Aug 17 10:18 : client: [68] process command "status"
Aug 17 10:18 : client: [68] command returned 0
Aug 17 10:18 : client: [68] process command "currentsong"
Aug 17 10:18 : client: [68] command returned 0
Aug 17 10:18 : client: [68] process command "close"
Aug 17 10:18 : client: [68] command returned 3
Aug 17 10:18 : client: [68] closed
Aug 17 10:18 : client: [69] opened from 127.0.0.1:49084
Aug 17 10:18 : client: [69] process command "lsinfo"
Aug 17 10:18 : client: [69] command returned 0
Aug 17 10:18 : client: [69] process command "close"
Aug 17 10:18 : client: [69] command returned 3
Aug 17 10:18 : client: [69] closed
Aug 17 10:18 : client: [70] opened from 127.0.0.1:49088
Aug 17 10:18 : client: [70] process command "close"
Aug 17 10:18 : client: [70] command returned 3
Aug 17 10:18 : client: [70] closed
Aug 17 10:18 : client: [71] opened from 127.0.0.1:49092
Aug 17 10:18 : client: [72] opened from 127.0.0.1:49096
Aug 17 10:18 : client: [72] process command "status"
Aug 17 10:18 : client: [72] command returned 0
Aug 17 10:18 : client: [72] process command "idle"
Aug 17 10:18 : client: [72] command returned 1
Aug 17 10:18 : client: [71] process command "playlistinfo"
Aug 17 10:18 : client: [71] command returned 0
Aug 17 10:18 : client: [71] process command "close"
Aug 17 10:18 : client: [71] command returned 3
Aug 17 10:18 : client: [71] closed
Aug 17 10:18 : client: [73] opened from 127.0.0.1:49100
Aug 17 10:18 : client: [73] process command "lsinfo "USB""
Aug 17 10:18 : client: [73] command returned 0
Aug 17 10:18 : client: [73] process command "close"
Aug 17 10:18 : client: [73] command returned 3
Aug 17 10:18 : client: [73] closed
Aug 17 10:18 : client: [74] opened from 127.0.0.1:49104
Aug 17 10:18 : client: [74] process command "lsinfo "USB/EXFAT-128GB""
Aug 17 10:18 : client: [74] command returned 0
Aug 17 10:18 : client: [74] process command "close"
Aug 17 10:18 : client: [74] command returned 3
Aug 17 10:18 : client: [74] closed
Aug 17 10:18 : client: [75] opened from 127.0.0.1:49108
Aug 17 10:18 : client: [75] process command "lsinfo "USB/EXFAT-128GB/Test_music""
Aug 17 10:18 : client: [75] command returned 0
Aug 17 10:18 : client: [75] process command "close"
Aug 17 10:18 : client: [75] command returned 3
Aug 17 10:18 : client: [75] closed
Aug 17 10:18 : client: [76] opened from 127.0.0.1:49112
Aug 17 10:18 : client: [76] process command "add "USB/EXFAT-128GB/Test_music/zippers""
Aug 17 10:18 : client: [76] command returned 0
Aug 17 10:18 : client: [76] process command "close"
Aug 17 10:18 : client: [76] command returned 3
Aug 17 10:18 : client: [76] closed
Aug 17 10:18 : client: [72] process command "status"
Aug 17 10:18 : client: [72] command returned 0
Aug 17 10:18 : client: [65] process command "status"
Aug 17 10:18 : client: [65] command returned 0
Aug 17 10:18 : client: [72] process command "currentsong"
Aug 17 10:18 : client: [72] command returned 0
Aug 17 10:18 : client: [65] process command "currentsong"
Aug 17 10:18 : client: [65] command returned 0
Aug 17 10:18 : client: [72] process command "close"
Aug 17 10:18 : client: [72] command returned 3
Aug 17 10:18 : client: [72] closed
Aug 17 10:18 : client: [65] process command "close"
Aug 17 10:18 : client: [65] command returned 3
Aug 17 10:18 : client: [65] closed
Aug 17 10:18 : client: [77] opened from 127.0.0.1:49116
Aug 17 10:18 : client: [77] process command "close"
Aug 17 10:18 : client: [77] command returned 3
Aug 17 10:18 : client: [77] closed
Aug 17 10:18 : client: [78] opened from 127.0.0.1:49120
Aug 17 10:18 : client: [79] opened from 127.0.0.1:49124
Aug 17 10:18 : client: [79] process command "status"
Aug 17 10:18 : client: [79] command returned 0
Aug 17 10:18 : client: [79] process command "idle"
Aug 17 10:18 : client: [79] command returned 1
Aug 17 10:18 : client: [78] process command "playlistinfo"
Aug 17 10:18 : client: [78] command returned 0
Aug 17 10:18 : client: [78] process command "close"
Aug 17 10:18 : client: [78] command returned 3
Aug 17 10:18 : client: [78] closed
Aug 17 10:18 : state_file: Saving state file /var/lib/mpd/state
Aug 17 10:18 : client: [80] opened from 127.0.0.1:49128
Aug 17 10:18 : client: [80] process command "play 49"
Aug 17 10:18 : playlist: play 49:"USB/EXFAT-128GB/Test_music/zippers/08 Ain't Gonna Rain Anymore.aif"
Aug 17 10:18 : client: [80] command returned 0
Aug 17 10:18 : playlist: queue song 50:"USB/EXFAT-128GB/Test_music/zippers/08 Pedestal.aif"
Aug 17 10:18 : client: [80] process command "close"
Aug 17 10:18 : client: [80] command returned 3
Aug 17 10:18 : client: [80] closed
Aug 17 10:18 : decoder_thread: probing plugin ffmpeg
Aug 17 10:18 : ffmpeg: detected input format 'aiff' (Audio IFF)
Aug 17 10:18 : ffmpeg/aiff: max_analyze_duration 5000000 reached
Aug 17 10:18 : ffmpeg: codec 'pcm_s16be'
Aug 17 10:18 : decoder: audio_format=44100:16:2, seekable=true
Aug 17 10:18 : decoder: converting to 384000:32:2
Aug 17 10:18 : soxr: soxr engine 'double-precision'
Aug 17 10:18 : soxr: samplerate conversion ratio to 8.71
Aug 17 10:18 : alsa_output: opened hw:0,0 type=HW
Aug 17 10:18 : alsa_output: buffer: size=64..65536 time=166..170667
Aug 17 10:18 : alsa_output: period: size=32..32768 time=83..85334
Aug 17 10:18 : alsa_output: default period_time = buffer_time/4 = 170666/4 = 42666
Aug 17 10:18 : alsa_output: format=S32_LE (Signed 32 bit Little Endian)
Aug 17 10:18 : alsa_output: buffer_size=65536 period_size=16384
Aug 17 10:18 : output: opened plugin=alsa name="ALSA default" audio_format=384000:32:2
Aug 17 10:18 : client: [79] process command "status"
Aug 17 10:18 : client: [79] command returned 0
Aug 17 10:18 : client: [79] process command "currentsong"
Aug 17 10:18 : client: [79] command returned 0
Aug 17 10:18 : client: [79] process command "close"
Aug 17 10:18 : client: [79] command returned 3
Aug 17 10:18 : client: [79] closed
Aug 17 10:18 : client: [81] opened from 127.0.0.1:49132
Aug 17 10:18 : client: [81] process command "close"
Aug 17 10:18 : client: [81] command returned 3
Aug 17 10:18 : client: [81] closed
Aug 17 10:18 : client: [82] opened from 127.0.0.1:49136
Aug 17 10:18 : client: [82] process command "status"
Aug 17 10:18 : client: [82] command returned 0
Aug 17 10:18 : client: [82] process command "idle"
Aug 17 10:18 : client: [82] command returned 1
Aug 17 10:18 : state_file: Saving state file /var/lib/mpd/state
Aug 17 10:18 : client: [83] opened from 127.0.0.1:49140
Aug 17 10:18 : client: [83] process command "play 50"
Aug 17 10:18 : playlist: play 50:"USB/EXFAT-128GB/Test_music/zippers/08 Pedestal.aif"
Aug 17 10:18 : decoder_thread: probing plugin ffmpeg
Aug 17 10:18 : ffmpeg: detected input format 'aiff' (Audio IFF)
Aug 17 10:18 : ffmpeg/aiff: max_analyze_duration 5000000 reached
Aug 17 10:18 : ffmpeg: codec 'pcm_s16be'
Aug 17 10:18 : decoder: audio_format=44100:16:2, seekable=true
Aug 17 10:18 : client: [83] command returned 0
Aug 17 10:18 : playlist: queue song 51:"USB/EXFAT-128GB/Test_music/zippers/11 It's Your Problem.aif"
Aug 17 10:18 : client: [83] process command "close"
Aug 17 10:18 : client: [83] command returned 3
Aug 17 10:18 : client: [83] closed
Aug 17 10:18 : client: [82] process command "status"
Aug 17 10:18 : client: [82] command returned 0
Aug 17 10:18 : client: [82] process command "currentsong"
Aug 17 10:18 : client: [82] command returned 0
Aug 17 10:18 : decoder: converting to 384000:32:2
Aug 17 10:18 : soxr: soxr engine 'double-precision'
Aug 17 10:18 : soxr: samplerate conversion ratio to 8.71
Aug 17 10:18 : client: [82] process command "close"
Aug 17 10:18 : client: [82] command returned 3
Aug 17 10:18 : client: [82] closed
Aug 17 10:18 : client: [84] opened from 127.0.0.1:49144
Aug 17 10:18 : client: [84] process command "close"
Aug 17 10:18 : client: [84] command returned 3
Aug 17 10:18 : client: [84] closed
Aug 17 10:18 : client: [85] opened from 127.0.0.1:49148
Aug 17 10:18 : client: [85] process command "status"
Aug 17 10:18 : client: [85] command returned 0
Aug 17 10:18 : client: [85] process command "idle"
Aug 17 10:18 : client: [85] command returned 1
Aug 17 10:18 : state_file: Saving state file /var/lib/mpd/state
Aug 17 10:18 : client: [86] opened from 127.0.0.1:49152
Aug 17 10:18 : client: [86] process command "play 51"
Aug 17 10:18 : playlist: play 51:"USB/EXFAT-128GB/Test_music/zippers/11 It's Your Problem.aif"
Aug 17 10:18 : decoder_thread: probing plugin ffmpeg
Aug 17 10:18 : ffmpeg: detected input format 'aiff' (Audio IFF)
Aug 17 10:18 : ffmpeg/aiff: max_analyze_duration 5000000 reached
Aug 17 10:18 : ffmpeg: codec 'pcm_s16be'
Aug 17 10:18 : decoder: audio_format=44100:16:2, seekable=true
Aug 17 10:18 : client: [86] command returned 0
Aug 17 10:18 : client: [85] process command "status"
Aug 17 10:18 : client: [85] command returned 0
Aug 17 10:18 : client: [86] process command "close"
Aug 17 10:18 : client: [86] command returned 3
Aug 17 10:18 : client: [86] closed
Aug 17 10:18 : decoder: converting to 384000:32:2
Aug 17 10:18 : client: [85] process command "currentsong"
Aug 17 10:18 : client: [85] command returned 0
Aug 17 10:18 : soxr: soxr engine 'double-precision'
Aug 17 10:18 : soxr: samplerate conversion ratio to 8.71
Aug 17 10:18 : client: [85] process command "close"
Aug 17 10:18 : client: [85] command returned 3
Aug 17 10:18 : client: [85] closed
Aug 17 10:18 : client: [87] opened from 127.0.0.1:49156
Aug 17 10:18 : client: [87] process command "close"
Aug 17 10:18 : client: [87] command returned 3
Aug 17 10:18 : client: [87] closed
Aug 17 10:18 : client: [88] opened from 127.0.0.1:49160
Aug 17 10:18 : client: [88] process command "status"
Aug 17 10:18 : client: [88] command returned 0
Aug 17 10:18 : client: [88] process command "idle"
Aug 17 10:18 : client: [88] command returned 1
Aug 17 10:18 : state_file: Saving state file /var/lib/mpd/state
Aug 17 10:19 : client: [89] opened from 127.0.0.1:49164
Aug 17 10:19 : client: [89] process command "pause"
Aug 17 10:19 : client: [89] command returned 0
Aug 17 10:19 : output: closed plugin=alsa name="ALSA default"
Aug 17 10:19 : client: [88] process command "status"
Aug 17 10:19 : client: [88] command returned 0
Aug 17 10:19 : client: [89] process command "close"
Aug 17 10:19 : client: [89] command returned 3
Aug 17 10:19 : client: [89] closed
Aug 17 10:19 : client: [88] process command "currentsong"
Aug 17 10:19 : client: [88] command returned 0
Aug 17 10:19 : client: [88] process command "close"
Aug 17 10:19 : client: [88] command returned 3
Aug 17 10:19 : client: [88] closed
Aug 17 10:19 : client: [90] opened from 127.0.0.1:49168
Aug 17 10:19 : client: [90] process command "close"
Aug 17 10:19 : client: [90] command returned 3
Aug 17 10:19 : client: [90] closed
Aug 17 10:19 : client: [91] opened from 127.0.0.1:49172
Aug 17 10:19 : client: [91] process command "status"
Aug 17 10:19 : client: [91] command returned 0
Aug 17 10:19 : client: [91] process command "idle"
Aug 17 10:19 : client: [91] command returned 1
Aug 17 10:19 : state_file: Saving state file /var/lib/mpd/state

CURRENTSONG INFO
================

pi@rp3:~ $ telnet localhost 6600
Trying ::1...
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
OK MPD 0.20.0
currentsong
file: USB/EXFAT-128GB/Test_music/zippers/08 Ain't Gonna Rain Anymore.aif
Last-Modified: 2017-08-12T19:11:04Z
Time: 226
duration: 226.000
Pos: 49
Id: 53
OK
currentsong
file: USB/EXFAT-128GB/Test_music/zippers/08 Pedestal.aif
Last-Modified: 2016-03-07T23:11:46Z
Time: 221
duration: 221.000
Pos: 50
Id: 54
OK
currentsong
file: USB/EXFAT-128GB/Test_music/zippers/11 It's Your Problem.aif
Last-Modified: 2016-03-09T10:05:39Z
Time: 67
duration: 67.307
Pos: 51
Id: 55
OK

MEDIAINFO DUMPS
===============
pi@rp3:~ $ mediainfo "/var/lib/mpd/music/USB/EXFAT-128GB/Test_music/zippers/08 Ain't Gonna Rain Anymore.aif"
General
Complete name                            : /var/lib/mpd/music/USB/EXFAT-128GB/Test_music/zippers/08 Ain't Gonna Rain Anymore.aif
Format                                   : AIFF
Format/Info                              : Apple/SGI
File size                                : 38.2 MiB
Duration                                 : 3mn 46s
Overall bit rate mode                    : Constant
Overall bit rate                         : 1 416 Kbps
Album                                    : Let Love In
Part/Position                            : 1
Part/Total                               : 1
Track name                               : Ain't Gonna Rain Anymore
Track name/Position                      : 8
Track name/Total                         : 10
Performer                                : Nick Cave & The Bad Seeds
Accompaniment                            : Nick Cave & The Bad Seeds
Composer                                 : Nick Cave/Nick Cave & The Bad Seeds
Genre                                    : Indie Rock
Recorded date                            : 1994
Cover                                    : Yes
Cover MIME                               : image/jpeg
iTunPGAP                                 : 0
iTunes_CDDB_1                            : 850B530A+217627+10+150+26938+44364+72975+85536+113329+132434+149595+166545+189700
iTunes_CDDB_TrackNumber                  : 8

Audio
Format                                   : PCM
Format settings, Endianness              : Big
Duration                                 : 3mn 46s
Bit rate mode                            : Constant
Bit rate                                 : 1 411.2 Kbps
Channel(s)                               : 2 channels
Sampling rate                            : 44.1 KHz
Bit depth                                : 16 bits
Stream size                              : 38.0 MiB (100%)

pi@rp3:~ $ mediainfo "/var/lib/mpd/music/USB/EXFAT-128GB/Test_music/zippers/08 Pedestal.aif"
General
Complete name                            : /var/lib/mpd/music/USB/EXFAT-128GB/Test_music/zippers/08 Pedestal.aif
Format                                   : AIFF
Format/Info                              : Apple/SGI
File size                                : 37.3 MiB
Duration                                 : 3mn 41s
Overall bit rate mode                    : Constant
Overall bit rate                         : 1 417 Kbps
Album                                    : Dummy
Part/Position                            : 1
Part/Total                               : 1
Track name                               : Pedestal
Track name/Position                      : 8
Track name/Total                         : 10
Performer                                : Portishead
Accompaniment                            : Portishead
Recorded date                            : 1994
Cover                                    : Yes
Cover MIME                               : image/jpeg
iTunPGAP                                 : 0
iTunes_CDDB_1                            : 740AAE0A+205265+10+182+23200+42247+60102+79592+101832+119677+142892+159467+182270
iTunes_CDDB_TrackNumber                  : 8

Audio
Format                                   : PCM
Format settings, Endianness              : Big
Duration                                 : 3mn 41s
Bit rate mode                            : Constant
Bit rate                                 : 1 411.2 Kbps
Channel(s)                               : 2 channels
Sampling rate                            : 44.1 KHz
Bit depth                                : 16 bits
Stream size                              : 37.2 MiB (100%)

pi@rp3:~ $ mediainfo "/var/lib/mpd/music/USB/EXFAT-128GB/Test_music/zippers/11 It's Your Problem.aif"
General
Complete name                            : /var/lib/mpd/music/USB/EXFAT-128GB/Test_music/zippers/11 It's Your Problem.aif
Format                                   : AIFF
Format/Info                              : Apple/SGI
File size                                : 11.6 MiB
Duration                                 : 1mn 7s
Overall bit rate mode                    : Constant
Overall bit rate                         : 1 444 Kbps
Album                                    : Things To Make And Do
Part/Position                            : 1
Part/Total                               : 1
Track name                               : It's Your Problem
Track name/Position                      : 11
Track name/Total                         : 18
Performer                                : Moloko
Accompaniment                            : Moloko
Recorded date                            : 2000
Cover                                    : Yes
Cover MIME                               : image/jpeg
iTunPGAP                                 : 0
iTunes_CDDB_1                            : F6100A12+308145+18+150+2037+31350+52765+78030+96557+113122+121990+142010+165880+187282+192330+215770+217645+243307+249127+264547+266137
iTunes_CDDB_TrackNumber                  : 11

Audio
Format                                   : PCM
Format settings, Endianness              : Big
Duration                                 : 1mn 7s
Bit rate mode                            : Constant
Bit rate                                 : 1 411.2 Kbps
Channel(s)                               : 2 channels
Sampling rate                            : 44.1 KHz
Bit depth                                : 16 bits
Stream size                              : 11.3 MiB (98%)

**Comment by MaxKellermann** [comment] 2017-08-18 15:21
Duplicate of #87

**Closed by MaxKellermann** 2017-08-18 15:21 UTC

**Comment by moodeaudio** [comment] 2017-08-18 18:40
Hi,

The FFMPEG params referenced in #87 don't work on any set of test AIFF files that I've received.

If I compile 0.19.19 using same config as 0.20.9 and then substitue it for 0.20.9 binary on same system then AIFF tags are read successfully. Same mpd.conf file except that for 0.19.19 the SoX resampler block is commented out.

The result seems to suggest a regression.

-Tim

===============
sudo wget http://www.musicpd.org/download/mpd/0.19/mpd-0.19.19.tar.xz
- compile using same config as 0.20.9 compile

================
pi@rp3:~ $ telnet localhost 6600
Trying ::1...
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
OK MPD 0.19.0
currentsong
file: USB/VFAT-8GB2/Test_mixed/zippers/08 Pedestal.aif
Last-Modified: 2016-03-07T10:11:46Z
Artist: Portishead
AlbumArtist: Portishead
Title: Pedestal
Album: Dummy
Track: 8/10
Date: 1994
Disc: 1/1
Time: 221
Pos: 57
Id: 58
OK
currentsong
file: USB/VFAT-8GB2/Test_mixed/zippers/08 Ain't Gonna Rain Anymore.aif
Last-Modified: 2017-08-12T06:11:04Z
Artist: Nick Cave & The Bad Seeds
AlbumArtist: Nick Cave & The Bad Seeds
Title: Ain't Gonna Rain Anymore
Album: Let Love In
Track: 8/10
Date: 1994
Genre: Indie Rock
Composer: Nick Cave/Nick Cave & The Bad Seeds
Disc: 1/1
Time: 226
Pos: 58
Id: 59
OK
currentsong
file: USB/VFAT-8GB2/Test_mixed/zippers/11 It's Your Problem.aif
Last-Modified: 2016-03-08T21:05:38Z
Artist: Moloko
AlbumArtist: Moloko
Title: It's Your Problem
Album: Things To Make And Do
Track: 11/18
Date: 2000
Disc: 1/1
Time: 67
Pos: 59
Id: 60
OK

================
pi@rp3:~ $ mpd -V
Music Player Daemon 0.19.19

Copyright (C) 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright (C) 2008-2014 Max Kellermann <max@duempel.org>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


Database plugins:
 simple proxy

Storage plugins:
 local

Decoders plugins:
 [mad] mp3 mp2
 [mpg123] mp3
 [vorbis] ogg oga
 [oggflac] ogg oga
 [flac] flac
 [dsdiff] dff
 [dsf] dsf
 [faad] aac
 [wavpack] wv
 [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tak tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve
 [pcm]

Output plugins:
 shout null fifo pipe alsa httpd recorder

Encoder plugins:
 null vorbis lame wave flac

Input plugins:
 file alsa curl ffmpeg cdio_paranoia

Playlist plugins:
 extm3u m3u pls soundcloud cue embcue

Protocols:
 file:// http:// https:// gopher:// rtp:// rtsp:// rtmp:// rtmpt:// rtmps:// cdda:// alsa://

================
follow_outside_symlinks "yes"
follow_inside_symlinks "yes"
db_file "/var/lib/mpd/tag_cache"
sticker_file "/var/lib/mpd/sticker.sql"
log_file "/var/log/mpd/mpd.log"
pid_file "/var/run/mpd/pid"
music_directory "/var/lib/mpd/music"
playlist_directory "/var/lib/mpd/playlists"
state_file "/var/lib/mpd/state"
user "mpd"
group "audio"
bind_to_address "any"
port "6600"
log_level "default"
zeroconf_enabled "yes"
zeroconf_name "RP3 MPD"
audio_output_format "384000:32:2"
volume_normalization "no"
audio_buffer_size "4096"
buffer_before_play "10%"
filesystem_charset "UTF-8"
id3v1_encoding "UTF-8"
gapless_mp3_playback "yes"
auto_update "no"
max_output_buffer_size "81920"
restore_paused "yes"
replaygain "off"
max_connections "20"

decoder {
plugin "ffmpeg"
enabled "yes"
}

input {
plugin "curl"
}

#resampler {
#plugin "soxr"
#quality "very high"
#threads "1"
#}

audio_output {
type "alsa"
name "ALSA default"
device "hw:0,0"
mixer_control "Master"
mixer_device "hw:0"
mixer_index "0"
dsd_usb "no"
}

audio_output {
type "alsa"
name "ALSA crossfeed"
device "crossfeed"
mixer_control "Master"
mixer_device "hw:0"
mixer_index "0"
dsd_usb "no"
}

audio_output {
type "alsa"
name "ALSA equalizer"
device "plug:plugequal"
mixer_control "Master"
mixer_device "hw:0"
mixer_index "0"
dsd_usb "no"
}

**Comment by moodeaudio** [comment] 2017-08-24 18:34
I can confirm that MPD 0.20.10 fixes AIFF tag issue with all my test files.

Thx Max.
