### ISSUE TITLE
Segfault with unknown reason.

### ISSUE THREAD

**Issue by sweetyoru** [MusicPlayerDaemon/MPD#1568] opened 2022-07-11 04:19 UTC
### Describe the bug
Segfault due to write into read-only mapped memory.

## Expected Behavior
Work normally.

## Actual Behavior
Segfault.

## Version

```
Music Player Daemon 0.23.7 (0.23.7)
Copyright 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2021 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple proxy upnp

Storage plugins:
 local udisks nfs curl

Neighbor plugins:
 upnp udisks

Decoders plugins:
 [mad] mp3 mp2
 [mpg123] mp3
 [vorbis] ogg oga
 [oggflac] ogg oga
 [flac] flac
 [opus] opus ogg oga
 [sndfile] wav aiff aif au snd paf iff svx sf voc w64 pvf xi htk caf sd2
 [audiofile] wav au aiff aif
 [dsdiff] dff
 [dsf] dsf
 [hybrid_dsd] m4a
 [faad] aac
 [wavpack] wv
 [openmpt] mptm mod s3m xm it 669 amf ams c67 dbm digi dmf dsm dtm far imf ice j2b m15 mdl med mms mt2 mtm nst okt plm psm pt36 ptm sfx sfx2 st26 stk stm stp ult wow gdm mo3 oxm umx xpk ppm mmcmp
 [modplug] 669 amf ams dbm dfm dsm far it med mdl mod mtm mt2 okt s3m stm ult umx xm
 [mikmod] amf dsm far gdm imf it med mod mtm s3m stm stx ult uni xm
 [sidplay] sid mus str prg P00
 [wildmidi] mid
 [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 adx afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tak tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve rtp:// rtsp:// rtsps://
 [pcm]

Filters:
 libsamplerate soxr

Tag plugins:
 id3tag

Output plugins:
 shout null fifo pipe alsa ao oss openal pipewire pulse jack httpd snapcast recorder

Encoder plugins:
 null vorbis opus lame twolame wave flac

Archive plugins:
 [bz2] bz2
 [zzip] zip
 [iso] iso

Input plugins:
 file io_uring archive alsa qobuz curl ffmpeg nfs mms cdio_paranoia

Playlist plugins:
 extm3u m3u pls xspf asx rss soundcloud flac cue embcue

Protocols:
 file:// alsa:// cdda:// ftp:// ftps:// gopher:// hls+http:// hls+https:// http:// https:// mms:// mmsh:// mmst:// mmsu:// nfs:// qobuz:// rtmp:// rtmpe:// rtmps:// rtmpt:// rtmpte:// rtp:// rtsp:// rtsps:// scp:// sftp:// smb:// srtp://

Other features:
 avahi dbus udisks epoll icu inotify ipv6 systemd tcp un
 ```

## Configuration

```
# An example configuration file for MPD.
# Read the user manual for documentation: http://www.musicpd.org/doc/user/


# Files and directories #######################################################
#
# This setting controls the top directory which MPD will search to discover the
# available audio files and add them to the daemon's online database. This
# setting defaults to the XDG directory, otherwise the music directory will be
# be disabled and audio files will only be accepted over ipc socket (using
# file:// protocol) or streaming files over an accepted protocol.
#
music_directory		"~/G/Musics"
#
# This setting sets the MPD internal playlist directory. The purpose of this
# directory is storage for playlists created by MPD. The server will use
# playlist files not created by the server but only if they are in the MPD
# format. This setting defaults to playlist saving being disabled.
#
playlist_directory		"~/.config/mpd/playlist"
#
# This setting sets the location of the MPD database. This file is used to
# load the database at server start up and store the database while the
# server is not up. This setting defaults to disabled which will allow
# MPD to accept files over ipc socket (using file:// protocol) or streaming
# files over an accepted protocol.
#
db_file			"~/.config/mpd/database"
#
# These settings are the locations for the daemon log files for the daemon.
# These logs are great for troubleshooting, depending on your log_level
# settings.
#
# The special value "syslog" makes MPD use the local syslog daemon. This
# setting defaults to logging to syslog.
#
log_file			"~/.config/mpd/log"
#
# This setting sets the location of the file which stores the process ID
# for use of mpd --kill and some init scripts. This setting is disabled by
# default and the pid file will not be stored.
#
pid_file			"~/.config/mpd/pid"
#
# This setting sets the location of the file which contains information about
# most variables to get MPD back into the same general shape it was in before
# it was brought down. This setting is disabled by default and the server
# state will be reset on server start up.
#
state_file			"~/.config/mpd/state"
#
# The location of the sticker database.  This is a database which
# manages dynamic information attached to songs.
#
sticker_file			"~/.config/mpd/sticker.sql"
#
###############################################################################


# General music daemon options ################################################
#
# This setting specifies the user that MPD will run as. MPD should never run as
# root and you may use this setting to make MPD change its user ID after
# initialization. This setting is disabled by default and MPD is run as the
# current user.
#
#user				"nobody"
#
# This setting specifies the group that MPD will run as. If not specified
# primary group of user specified with "user" setting will be used (if set).
# This is useful if MPD needs to be a member of group such as "audio" to
# have permission to use sound card.
#
#group				"nogroup"
#
# This setting sets the address for the daemon to listen on. Careful attention
# should be paid if this is assigned to anything other then the default, any.
# This setting can deny access to control of the daemon. Not effective if
# systemd socket activiation is in use.
#
# For network
bind_to_address		"localhost"
#
# And for Unix Socket
#bind_to_address		"~/.config/mpd/socket"
#
# This setting is the TCP port that is desired for the daemon to get assigned
# to.
#
port				"6600"
#
# This setting controls the type of information which is logged. Available
# setting arguments are "default", "secure" or "verbose". The "verbose" setting
# argument is recommended for troubleshooting, though can quickly stretch
# available resources on limited hardware storage.
#
log_level			"default"
#
# Setting "restore_paused" to "yes" puts MPD into pause mode instead
# of starting playback after startup.
#
#restore_paused "no"
#
# This setting enables MPD to create playlists in a format usable by other
# music players.
#
save_absolute_paths_in_playlists	"no"
#
# This setting defines a list of tag types that will be extracted during the
# audio file discovery process. The complete list of possible values can be
# found in the user manual.
#metadata_to_use	"artist,album,title,track,name,genre,date,composer,performer,disc"
#
# This example just enables the "comment" tag without disabling all
# the other supported tags:
#metadata_to_use "+comment"
#
# This setting enables automatic update of MPD's database when files in
# music_directory are changed.
#
auto_update	"yes"
#
# Limit the depth of the directories being watched, 0 means only watch
# the music directory itself.  There is no limit by default.
#
#auto_update_depth "3"
#
###############################################################################


# Symbolic link behavior ######################################################
#
# If this setting is set to "yes", MPD will discover audio files by following
# symbolic links outside of the configured music_directory.
#
follow_outside_symlinks	"yes"
#
# If this setting is set to "yes", MPD will discover audio files by following
# symbolic links inside of the configured music_directory.
#
follow_inside_symlinks		"yes"
#
###############################################################################


# Zeroconf / Avahi Service Discovery ##########################################
#
# If this setting is set to "yes", service information will be published with
# Zeroconf / Avahi.
#
zeroconf_enabled		"no"
#
# The argument to this setting will be the Zeroconf / Avahi unique name for
# this MPD server on the network. %h will be replaced with the hostname.
#
#zeroconf_name			"Music Player @ %h"
#
###############################################################################


# Permissions #################################################################
#
# If this setting is set, MPD will require password authorization. The password
# setting can be specified multiple times for different password profiles.
#
#password                        "password@read,add,control,admin"
#
# This setting specifies the permissions a user has who has not yet logged in.
#
#default_permissions             "read,add,control,admin"
#
###############################################################################


# Database #######################################################################
#

#database {
#       plugin "proxy"
#       host "other.mpd.host"
#       port "6600"
#}

# Input #######################################################################
#

#input {
#        plugin "curl"
#       proxy "proxy.isp.com:8080"
#       proxy_user "user"
#       proxy_password "password"
#}

#
###############################################################################

# Audio Output ################################################################
#
# MPD supports various audio output types, as well as playing through multiple
# audio outputs at the same time, through multiple audio_output settings
# blocks. Setting this block is optional, though the server will only attempt
# autodetection for one sound card.
#
# An example of an ALSA output:
#
#audio_output {
#	type		"alsa"
#	name		"My ALSA Device"
##	device		"hw:0,0"	# optional
##	mixer_type      "hardware"	# optional
##	mixer_device	"default"	# optional
##	mixer_control	"PCM"		# optional
##	mixer_index	"0"		# optional
#}
#
# An example of an OSS output:
#
#audio_output {
#	type		"oss"
#	name		"My OSS Device"
##	device		"/dev/dsp"	# optional
##	mixer_type      "hardware"	# optional
##	mixer_device	"/dev/mixer"	# optional
##	mixer_control	"PCM"		# optional
#}
#
# An example of a shout output (for streaming to Icecast):
#
#audio_output {
#	type		"shout"
#	encoder		"vorbis"		# optional
#	name		"My Shout Stream"
#	host		"localhost"
#	port		"8000"
#	mount		"/mpd.ogg"
#	password	"hackme"
#	quality		"5.0"
#	bitrate		"128"
#	format		"44100:16:1"
##	protocol	"icecast2"		# optional
##	user		"source"		# optional
##	description	"My Stream Description"	# optional
##	url		"http://example.com"	# optional
##	genre		"jazz"			# optional
##	public		"no"			# optional
##	timeout		"2"			# optional
##	mixer_type      "software"		# optional
#}
#
# An example of a recorder output:
#
#audio_output {
#	type		"recorder"
#	name		"My recorder"
#	encoder		"vorbis"		# optional, vorbis or lame
#	path		"/var/lib/mpd/recorder/mpd.ogg"
##	quality		"5.0"			# do not define if bitrate is defined
#	bitrate		"128"			# do not define if quality is defined
#	format		"44100:16:1"
#}
#
# An example of a httpd output (built-in HTTP streaming server):
#
#audio_output {
#	type		"httpd"
#	name		"My HTTP Stream"
#	encoder		"vorbis"		# optional, vorbis or lame
#	port		"8000"
#	bind_to_address	"0.0.0.0"		# optional, IPv4 or IPv6
##	quality		"5.0"			# do not define if bitrate is defined
#	bitrate		"128"			# do not define if quality is defined
#	format		"44100:16:1"
#	max_clients	"0"			# optional 0=no limit
#}
#
# An example of a pulseaudio output (streaming to a remote pulseaudio server)
#
#audio_output {
#	type		"pulse"
#	name		"My Pulse Output"
##	server		"remote_server"		# optional
##	sink		"remote_server_sink"	# optional
#}
#
# An example of a winmm output (Windows multimedia API).
#
#audio_output {
#	type		"winmm"
#	name		"My WinMM output"
##	device		"Digital Audio (S/PDIF) (High Definition Audio Device)" # optional
#		or
##	device		"0"		# optional
##	mixer_type	"hardware"	# optional
#}
#
# An example of an openal output.
#
#audio_output {
#	type		"openal"
#	name		"My OpenAL output"
##	device		"Digital Audio (S/PDIF) (High Definition Audio Device)" # optional
#}
#
# An example of an sndio output.
#
#audio_output {
#	type		"sndio"
#	name		"sndio output"
#	mixer_type	"hardware"
#}
#
# An example of an OS X output:
#
#audio_output {
#	type		"osx"
#	name		"My OS X Device"
##	device		"Built-in Output"	# optional
##	channel_map      "-1,-1,0,1"	# optional
#}
#
## Example "pipe" output:
#
#audio_output {
#	type		"pipe"
#	name		"my pipe"
#	command		"aplay -f cd 2>/dev/null"
## Or if you're want to use AudioCompress
#	command		"AudioCompress -m | aplay -f cd 2>/dev/null"
## Or to send raw PCM stream through PCM:
#	command		"nc example.org 8765"
#	format		"44100:16:2"
#}
#
## An example of a null output (for no audio output):
#
#audio_output {
#	type		"null"
#	name		"My Null Output"
#	mixer_type      "none"			# optional
#}
#
###############################################################################

audio_output {
	type "pulse"
	name "Pulseaudio"
}

audio_output {
	type "pipewire"
	name "PipeWire"
	auto_resample "no"
	auto_format   "yes"
	auto_channels "no"
	format "96000:32:2"
}

audio_output {
	type "alsa"
	name "Fiio"
	device "hw:1,0"
	always_on "yes"
	auto_resample "no"
	auto_format   "yes"
	auto_channels "no"
 	mixer_type    "none"
	format "96000:32:2"
}


# set resampler plugin to Secret Rabbit Code type 0 (best quality)
resampler {
  plugin "libsamplerate"
  type "0"
}

# Normalization automatic volume adjustments ##################################
#
# This setting specifies the type of ReplayGain to use. This setting can have
# the argument "off", "album", "track" or "auto". "auto" is a special mode that
# chooses between "track" and "album" depending on the current state of
# random playback. If random playback is enabled then "track" mode is used.
# See <http://www.replaygain.org> for more details about ReplayGain.
# This setting is off by default.
#
replaygain			"off"
#
# This setting sets the pre-amp used for files that have ReplayGain tags. By
# default this setting is disabled.
#
#replaygain_preamp		"0"
#
# This setting sets the pre-amp used for files that do NOT have ReplayGain tags.
# By default this setting is disabled.
#
replaygain_missing_preamp	"0"
#
# This setting enables or disables ReplayGain limiting.
# MPD calculates actual amplification based on the ReplayGain tags
# and replaygain_preamp / replaygain_missing_preamp setting.
# If replaygain_limit is enabled MPD will never amplify audio signal
# above its original level. If replaygain_limit is disabled such amplification
# might occur. By default this setting is enabled.
#
replaygain_limit		"yes"
#
# This setting enables on-the-fly normalization volume adjustment. This will
# result in the volume of all playing audio to be adjusted so the output has
# equal "loudness". This setting is disabled by default.
#
volume_normalization		"no"
#
###############################################################################

# Character Encoding ##########################################################
#
# If file or directory names do not display correctly for your locale then you
# may need to modify this setting.
#
#filesystem_charset		"UTF-8"
#
###############################################################################
```

## Log

[d.core.zip](https://github.com/MusicPlayerDaemon/MPD/files/9080874/d.core.zip)
A core file is provided.

## coredumpctl output:

```
  ➜ coredumpctl dump mpd
           PID: 3297 (mpd)
           UID: 1000 (yoru)
           GID: 1000 (yoru)
        Signal: 11 (SEGV)
     Timestamp: Mon 2022-07-11 09:53:45 +07 (1h 28min ago)
  Command Line: /usr/bin/mpd --systemd
    Executable: /usr/bin/mpd
 Control Group: /user.slice/user-1000.slice/user@1000.service/app.slice/mpd.service
          Unit: user@1000.service
     User Unit: mpd.service
         Slice: user-1000.slice
     Owner UID: 1000 (yoru)
       Boot ID: 9988c248d93a42e8962cba1338394b6a
    Machine ID: 29409f2da40d44e18aa39c35fd642223
      Hostname: bittersweet
       Storage: /var/lib/systemd/coredump/core.mpd.1000.9988c248d93a42e8962cba1338394b6a.3297.1657508025000000.zst (present)
     Disk Size: 9.2M
       Message: Process 3297 (mpd) of user 1000 dumped core.

                Module linux-vdso.so.1 with build-id 7ba055749a97c4f286f422b43f34916868c7574f
                Module libspa-audioconvert.so with build-id a324fa6aaab4286db936af8adaa28d42089b93ff
                Metadata for module libspa-audioconvert.so owned by FDO found: {
                	"type" : "rpm",
                	"name" : "pipewire",
                	"version" : "0.3.54-1.fc36",
                	"architecture" : "x86_64",
                	"osCpe" : "cpe:/o:fedoraproject:fedora:36"
                }

                Module libpipewire-module-session-manager.so with build-id b64b296ab9a6e26ba2243ee08ab4affe90bc0448
                Metadata for module libpipewire-module-session-manager.so owned by FDO found: {
                	"type" : "rpm",
                	"name" : "pipewire",
                	"version" : "0.3.54-1.fc36",
                	"architecture" : "x86_64",
                	"osCpe" : "cpe:/o:fedoraproject:fedora:36"
                }

                Module libpipewire-module-metadata.so with build-id 626b623ee22de01d7552e81f347155bbd9d26162
                Metadata for module libpipewire-module-metadata.so owned by FDO found: {
                	"type" : "rpm",
                	"name" : "pipewire",
                	"version" : "0.3.54-1.fc36",
                	"architecture" : "x86_64",
                	"osCpe" : "cpe:/o:fedoraproject:fedora:36"
                }

                Module libpipewire-module-adapter.so with build-id 04d6377d614bc05aa5c79cc561da14038ad17d1a
                Metadata for module libpipewire-module-adapter.so owned by FDO found: {
                	"type" : "rpm",
                	"name" : "pipewire",
                	"version" : "0.3.54-1.fc36",
                	"architecture" : "x86_64",
                	"osCpe" : "cpe:/o:fedoraproject:fedora:36"
                }

                Module libpipewire-module-client-device.so with build-id 19e5be87cb27ba90f39a0663491694ceb1854ada
                Metadata for module libpipewire-module-client-device.so owned by FDO found: {
                	"type" : "rpm",
                	"name" : "pipewire",
                	"version" : "0.3.54-1.fc36",
                	"architecture" : "x86_64",
                	"osCpe" : "cpe:/o:fedoraproject:fedora:36"
                }

                Module libpipewire-module-client-node.so with build-id 5311758e197658c553831a86d618fcb8c4f46dba
                Metadata for module libpipewire-module-client-node.so owned by FDO found: {
                	"type" : "rpm",
                	"name" : "pipewire",
                	"version" : "0.3.54-1.fc36",
                	"architecture" : "x86_64",
                	"osCpe" : "cpe:/o:fedoraproject:fedora:36"
                }

                Module libpipewire-module-protocol-native.so with build-id 272c405364c94a4b2ae2c622fb43a0afa43c8da4
                Metadata for module libpipewire-module-protocol-native.so owned by FDO found: {
                	"type" : "rpm",
                	"name" : "pipewire",
                	"version" : "0.3.54-1.fc36",
                	"architecture" : "x86_64",
                	"osCpe" : "cpe:/o:fedoraproject:fedora:36"
                }

                Module libspa-dbus.so with build-id 5ceacdd83e62833b21cb88a3a555a6df8c645c6e
                Metadata for module libspa-dbus.so owned by FDO found: {
                	"type" : "rpm",
                	"name" : "pipewire",
                	"version" : "0.3.54-1.fc36",
                	"architecture" : "x86_64",
                	"osCpe" : "cpe:/o:fedoraproject:fedora:36"
                }

                Module libspa-journal.so with build-id c64407882cb41f9df1486a0aeb86305679b556f5
                Metadata for module libspa-journal.so owned by FDO found: {
                	"type" : "rpm",
                	"name" : "pipewire",
                	"version" : "0.3.54-1.fc36",
                	"architecture" : "x86_64",
                	"osCpe" : "cpe:/o:fedoraproject:fedora:36"
                }

                Module libspa-support.so with build-id 9b38788e66f9aaf2959bd2b63d0e7b974f834cf7
                Metadata for module libspa-support.so owned by FDO found: {
                	"type" : "rpm",
                	"name" : "pipewire",
                	"version" : "0.3.54-1.fc36",
                	"architecture" : "x86_64",
                	"osCpe" : "cpe:/o:fedoraproject:fedora:36"
                }

                Module libjbig.so.2.1 with build-id 208c20ec20c71e7cce019a94027f0c811f89fdba
                Metadata for module libjbig.so.2.1 owned by FDO found: {
                	"type" : "rpm",
                	"name" : "jbigkit",
                	"version" : "2.1-23.fc36",
                	"architecture" : "x86_64",
                	"osCpe" : "cpe:/o:fedoraproject:fedora:36"
                }

                Module libdatrie.so.1 with build-id 768a842bc0741478ded11a6209b709b6ff6ea43f
                Stack trace of thread 143202:
                #0  0x00007f19e00ee67a conv_s32_to_f32d_avx2 (libspa-audioconvert.so + 0x4767a)
                #1  0x00007f19e00db544 impl_node_process (libspa-audioconvert.so + 0x34544)
                #2  0x00007f19e00bfcff impl_node_process (libspa-audioconvert.so + 0x18cff)
                #3  0x00007f19ed72f549 process_node (libpipewire-0.3.so.0 + 0x61549)
                #4  0x00007f19ed732b6c node_on_fd_events (libpipewire-0.3.so.0 + 0x64b6c)
                #5  0x00007f19f01b64ad loop_iterate (libspa-support.so + 0x74ad)
                #6  0x00007f19ed7103b7 do_loop (libpipewire-0.3.so.0 + 0x423b7)
                #7  0x00007f19eb28ce2d start_thread (libc.so.6 + 0x8ce2d)
                #8  0x00007f19eb3117d4 __clone (libc.so.6 + 0x1117d4)

                Stack trace of thread 3297:
                #0  0x00007f19eb311bfe epoll_wait (libc.so.6 + 0x111bfe)
                #1  0x000055fffa0308c1 _ZN9EventLoop3RunEv (mpd + 0x978c1)
                #2  0x000055fff9ff0f68 _ZL14MainConfiguredRK18CommandLineOptionsRK10ConfigData (mpd + 0x57f68)
                #3  0x000055fff9ff213c _ZL11MainOrThrowiPPc (mpd + 0x5913c)
                #4  0x000055fff9fe9bee main (mpd + 0x50bee)
                #5  0x00007f19eb229550 __libc_start_call_main (libc.so.6 + 0x29550)
                #6  0x00007f19eb229609 __libc_start_main@@GLIBC_2.34 (libc.so.6 + 0x29609)
                #7  0x000055fff9fe9f15 _start (mpd + 0x50f15)

                Stack trace of thread 3619:
                #0  0x00007f19eb311bfe epoll_wait (libc.so.6 + 0x111bfe)
                #1  0x000055fffa0308c1 _ZN9EventLoop3RunEv (mpd + 0x978c1)
                #2  0x000055fffa02d3c7 _ZN6Thread10ThreadProcEPv (mpd + 0x943c7)
                #3  0x00007f19eb28ce2d start_thread (libc.so.6 + 0x8ce2d)
                #4  0x00007f19eb3117d4 __clone (libc.so.6 + 0x1117d4)

                Stack trace of thread 143198:
                #0  0x00007f19eb289a19 __futex_abstimed_wait_common (libc.so.6 + 0x89a19)
                #1  0x00007f19eb28c210 pthread_cond_wait@@GLIBC_2.3.2 (libc.so.6 + 0x8c210)
                #2  0x00007f19eb6d50d0 _ZNSt18condition_variable4waitERSt11unique_lockISt5mutexE (libstdc++.so.6 + 0xd50d0)
                #3  0x000055fffa00ac6f _ZN13PlayerControl18WaitOutputConsumedERSt11unique_lockISt5mutexEj (mpd + 0x71c6f)
                #4  0x000055fffa011daf _ZN13PlayerControl9RunThreadEv (mpd + 0x78daf)
                #5  0x000055fffa02d3c7 _ZN6Thread10ThreadProcEPv (mpd + 0x943c7)
                #6  0x00007f19eb28ce2d start_thread (libc.so.6 + 0x8ce2d)
                #7  0x00007f19eb3117d4 __clone (libc.so.6 + 0x1117d4)

                Stack trace of thread 143200:
                #0  0x00007f19eb289a19 __futex_abstimed_wait_common (libc.so.6 + 0x89a19)
                #1  0x00007f19eb28c210 pthread_cond_wait@@GLIBC_2.3.2 (libc.so.6 + 0x8c210)
                #2  0x00007f19ed75f56a pw_thread_loop_wait (libpipewire-0.3.so.0 + 0x9156a)
                #3  0x000055fffa06d1ed _ZN14PipeWireOutput4PlayEPKvm (mpd + 0xd41ed)
                #4  0x000055fffa05e1dc _ZN16BindMethodDetail16WrapperGeneratorIM18AudioOutputControlDoFvvEXadL_ZNS1_4TaskEvEEE6InvokeEPv (mpd + 0xc51dc)
                #5  0x000055fffa02d3c7 _ZN6Thread10ThreadProcEPv (mpd + 0x943c7)
                #6  0x00007f19eb28ce2d start_thread (libc.so.6 + 0x8ce2d)
                #7  0x00007f19eb3117d4 __clone (libc.so.6 + 0x1117d4)

                Stack trace of thread 3620:
                #0  0x00007f19eb311bfe epoll_wait (libc.so.6 + 0x111bfe)
                #1  0x000055fffa0308c1 _ZN9EventLoop3RunEv (mpd + 0x978c1)
                #2  0x000055fffa02d3c7 _ZN6Thread10ThreadProcEPv (mpd + 0x943c7)
                #3  0x00007f19eb28ce2d start_thread (libc.so.6 + 0x8ce2d)
                #4  0x00007f19eb3117d4 __clone (libc.so.6 + 0x1117d4)

                Stack trace of thread 143201:
                #0  0x00007f19eb311bfe epoll_wait (libc.so.6 + 0x111bfe)
                #1  0x00007f19f01c3a18 impl_pollfd_wait (libspa-support.so + 0x14a18)
                #2  0x00007f19f01b6371 loop_iterate (libspa-support.so + 0x7371)
                #3  0x00007f19ed75ee12 do_loop (libpipewire-0.3.so.0 + 0x90e12)
                #4  0x00007f19eb28ce2d start_thread (libc.so.6 + 0x8ce2d)
                #5  0x00007f19eb3117d4 __clone (libc.so.6 + 0x1117d4)

                Stack trace of thread 143199:
                #0  0x00007f19eb289a19 __futex_abstimed_wait_common (libc.so.6 + 0x89a19)
                #1  0x00007f19eb28c210 pthread_cond_wait@@GLIBC_2.3.2 (libc.so.6 + 0x8c210)
                #2  0x00007f19eb6d50d0 _ZNSt18condition_variable4waitERSt11unique_lockISt5mutexE (libstdc++.so.6 + 0xd50d0)
                #3  0x000055fff9ffdb34 _ZN13DecoderBridge8GetChunkEv.part.0 (mpd + 0x64b34)
                #4  0x000055fffa009598 _ZN13DecoderBridge10SubmitDataEP11InputStreamPKvmt (mpd + 0x70598)
                #5  0x000055fffa07e82b _ZL20flac_decode_internalR13DecoderClientR11InputStreamb (mpd + 0xe582b)
                #6  0x000055fff9ff6e46 _ZL21decoder_stream_decodeRK13DecoderPluginR13DecoderBridgeR11InputStreamRSt11unique_lockISt5mutexE (mpd + 0x5de46)
                #7  0x000055fff9ffc91d _ZL11decoder_runR14DecoderControl.lto_priv.0 (mpd + 0x6391d)
                #8  0x000055fff9ffdede _ZN16BindMethodDetail16WrapperGeneratorIM14DecoderControlDoFvvEXadL_ZNS1_9RunThreadEvEEE6InvokeEPv (mpd + 0x64ede)
                #9  0x000055fffa02d3c7 _ZN6Thread10ThreadProcEPv (mpd + 0x943c7)
                #10 0x00007f19eb28ce2d start_thread (libc.so.6 + 0x8ce2d)
                #11 0x00007f19eb3117d4 __clone (libc.so.6 + 0x1117d4)
                ELF object binary architecture: AMD x86-64
```

**Comment by MaxKellermann** [comment] 2022-07-11 13:30
This looks like a crash in libspa/libpipewire and not related to MPD.

**Comment by wtay** [comment] 2022-07-11 14:44
> @wtay Pipewire is still killing mpd

What version are you running? maybe try git master of pipewire?

**Comment by wtay** [comment] 2022-07-11 15:24
> It's crashing with the latest in F36.

Ok, you will have to either downgrade or wait till the next version later this week.

**Comment by sweetyoru** [comment] 2022-07-11 15:25
Next version of mpd or pipewire?

**Comment by wtay** [comment] 2022-07-11 15:52
next version of pipewire.

**Comment by MaxKellermann** [comment] 2022-07-11 15:53
Thanks @wtay for dropping by and helping out.
@sweetyoru PipeWire, I think. He's the PipeWire guy.

Bugs like this one are difficult to judge - what looks like a PipeWire bug can be a MPD bug after all, if MPD passes wrong parameters to libpipewire; this always needs a closer look. In this case, the backtrace shows that this happens inside a thread created by libpipewire, with only libpipewire (and libspa) on the stack. This makes it very unlikely to be caused by MPD.

We had other bug reports with incomplete backtraces that also looked like PipeWire bugs (e.g. https://github.com/MusicPlayerDaemon/MPD/issues/1558), but turned out to be MPD bugs; or rather a PipeWire version with a different behavior, with a null pointer where never was a null pointer before, and no documentation on whether a null pointer was allowed. Reality is sometimes more complex than desired ;-)

**Comment by wtay** [comment] 2022-07-11 16:04
in this case I think it's pipewire fault. There was a bug in audioconvert where it would read more data then was available, which could explain this.

**Comment by sweetyoru** [comment] 2022-07-12 02:50
That is a write instruction, so maybe audioconvert guys also need to check for data write too.

**Comment by wtay** [comment] 2022-07-12 05:43
> That is a write instruction, so maybe audioconvert guys also need to check for data write too.

Yes, one end was reading too much, the other writing too much.

I can't run mpd myself so i can't test with the maser version of pipewire if it's fixed now. If you could test that would be great, otherwise we have to hope it's working in the next release (very soon).

**Comment by sweetyoru** [comment] 2022-07-12 13:15
> > That is a write instruction, so maybe audioconvert guys also need to check for data write too.
> 
> Yes, one end was reading too much, the other writing too much.
> 
> I can't run mpd myself so i can't test with the maser version of pipewire if it's fixed now. If you could test that would be great, otherwise we have to hope it's working in the next release (very soon).

I will need to wait for the new release to make it to fedora's repo, since messing with the package isn't a good idea. Thank you very much for the help.

**Comment by leigh123linux** [comment] 2022-07-12 14:13
@sweetyoru  You can get the latest builds using

```
sudo dnf install koji; mkdir pipewire;cd pipewire;koji download-build --arch=x86_64 2000504;sudo dnf update *rpm
sudo dnf --enablrepo=r*g update mpd*
```

**Comment by wtay** [comment] 2022-07-12 14:33
the f36 update: https://bodhi.fedoraproject.org/updates/FEDORA-2022-45a1c6b1c9

**Comment by sweetyoru** [comment] 2022-07-13 03:47
I can't reproduce the crash, so I can't confirm if the update work or not. Need to wait for others to bump into this.

**Closed** 2022-07-15 08:23 UTC
Labels: thirdparty
