### ISSUE TITLE
with pipewire, playback stalls upon switching tracks if using default/alsa audio output

### ISSUE THREAD

**Issue by nothingmuch** [MusicPlayerDaemon/MPD#1649] opened 2022-10-16 22:49 UTC
### Describe the bug

During the playing state, switching tracks (e.g. mpc next) outputs silence, playback does not advance but the reported state is still "playing". Playback resumed upon pausing and unpausing. During this state `pavucontrol` still shows an alsa playback stream (not sure if this is the right terminology) attributed to mpd, which differs from the paused state (not visible in pavucontrol).

When playback is paused, switching tracks works as expected (playback begins).

## Workaround

Switching to the `pulse` or `pipewire` audio output types, e.g. with the following configuration completely works around this issue.

```
audio_output {
        type            "pulse"
        name            "Pulse Output"
        mixer_control   "Master"
}
```

Because this resolved my issue and I'm only just getting started with learning how mpd works I did not investigate further.

I suspect this might be related to #1354 but for me playback stalls indefinitely. In that issue the following audio output is used (both this following and the previous configs are verified working with my version):

```
audio_output {
  type "pipewire"
  name "PipeWire"
}
```

Since it seems like a new issue, despite not actually affecting me I thought it was worth reporting in case the output detection logic is revised to take this into account or if someone else thinks the root cause is worth addressing.

I'm happy to try and dig deeper I will need some guidance as this is all new to me, and not sure what to do next other than verifying it's still an issue in master (I'm using mpd from nixpkgs and it's one released version behind).

## Expected Behavior

After switching tracks playback should begin without needing to toggle paused state twice.

## Actual Behavior

Playback stalls until toggling pause state

## Version

```
Music Player Daemon 0.23.9 (0.23.9)
Copyright 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2021 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple proxy

Storage plugins:
 local smbclient udisks nfs curl

Neighbor plugins:
 smbclient udisks

Decoders plugins:
 [mad] mp3 mp2
 [mpg123] mp3
 [vorbis] ogg oga
 [oggflac] ogg oga
 [flac] flac
 [opus] opus ogg oga
 [audiofile] wav au aiff aif
 [dsdiff] dff
 [dsf] dsf
 [hybrid_dsd] m4a
 [faad] aac
 [mikmod] amf dsm far gdm imf it med mod mtm s3m stm stx ult uni xm
 [fluidsynth] mid
 [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 adx afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tak tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve rtp:// rtsp:// rtsps://
 [gme] ay gbs gym hes kss nsf nsfe rsn sap spc vgm vgz
 [pcm]

Filters:
 libsamplerate

Tag plugins:
 id3tag

Output plugins:
 shout null fifo pipe alsa pipewire pulse jack httpd snapcast recorder

Encoder plugins:
 null vorbis opus lame wave flac

Archive plugins:
 [bz2] bz2
 [zzip] zip

Input plugins:
 file io_uring archive alsa qobuz curl ffmpeg smbclient nfs mms

Playlist plugins:
 extm3u m3u pls xspf asx rss soundcloud flac cue embcue

Protocols:
 file:// alsa:// ftp:// ftps:// gopher:// hls+http:// hls+https:// http:// https:// mms:// mmsh:// mmst:// mmsu:// nfs:// qobuz:// rtmp:// rtmps:// rtmpt:// rtmpts:// rtp:// rtsp:// rtsps:// scp:// sftp:// smb:// srtp://

Other features:
 avahi dbus udisks epoll icu inotify systemd tcp un
```

## Configuration

This is generated by nix/home-manager, with default settings (`services.mpd.enable = true` and `xdg.userDirs.enable = true`).

```
music_directory     "/home/user/Music"
playlist_directory  "/home/user/.local/share/mpd/playlists"
db_file             "/home/user/.local/share/mpd/tag_cache"

state_file          "/home/user/.local/share/mpd/state"
sticker_file        "/home/user/.local/share/mpd/sticker.sql"

bind_to_address "127.0.0.1"
```

## Log

There is no log output when this bug manifests (when switching tracks), the incuded output is only the startup sequence.

```
mpd --verbose --no-daemon /nix/store/my0cc0ij7wj6l1qphq9l50rsv734qq1q-mpd.conf
config_file: loading file /nix/store/my0cc0ij7wj6l1qphq9l50rsv734qq1q-mpd.conf
libsamplerate: libsamplerate converter 'Fastest Sinc Interpolator'
vorbis: Xiph.Org libVorbis 1.3.7
opus: libopus 1.3.1
hybrid_dsd: The Hybrid DSD decoder is disabled because it was not explicitly enabled
simple_db: reading DB
output: No 'audio_output' defined in config file
output: Attempt to detect audio output device
output: Attempting to detect a alsa audio device
output: Successfully detected a alsa audio device
input: Input plugin 'qobuz' is not configured: No Qobuz app_id configured
curl: version 7.85.0
curl: with OpenSSL/3.0.5
```

**Comment by MaxKellermann** [comment] 2022-11-06 09:19
Your log shows that you never started playback and that there was never a song change.

**Comment by MaxKellermann** [comment] 2022-11-08 13:52
Duplicate of #1645

**Closed by MaxKellermann** 2022-11-08 13:52 UTC
Labels: incomplete

**Comment by MightyPork** [comment] 2024-05-30 09:10
This bug remains on arch in the default mpd configuration.

I don't see any crash, but playback is paused after switching tracks within the same album. Hitting play/pause twice makes it play again.

Fixed by adding this to the config file:

```
audio_output {
  type "pulse"
  name "Pipewire Playback"
}
```
