### ISSUE TITLE
Failed to initialize io_uring

### ISSUE THREAD

**Issue by ian-s-mcb** [MusicPlayerDaemon/MPD#987] opened 2020-10-23 03:02 UTC
### Describe the bug
After updating version 0.22, MPD stopped retaining the state (playlist items, current track, etc) between service restarts or OS reboots. When starting the service, the service logs the following memory allocation error, which may be the root cause.

`Failed to initialize io_uring: io_uring_queue_init() failed: Cannot allocate memory`

This issue is similar to,  if not the same as, issues #972 and #984, but the conversation in those bug report didn't lead to a solution for me.

Thank you for your time and advice.

## Expected Behavior
MPD retains the state after service restarts using the `state` file.

## Actual Behavior
MPD doesn't retain the state. Although tracks were in the playlist before the service was restarted, the playlist shows up as empty.

## Version
```
$ mpd --version
Music Player Daemon 0.23~git (v0.22.1-67-gad585e179+)
Copyright 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2018 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple proxy upnp

Storage plugins:
 local smbclient udisks nfs curl

Neighbor plugins:
 smbclient upnp udisks

Decoders plugins:
 [mad] mp3 mp2
 [mpg123] mp3
 [vorbis] ogg oga
 [oggflac] ogg oga
 [flac] flac
 [opus] opus ogg oga
 [sndfile] wav aiff aif au snd paf iff svx sf voc w64 pvf xi htk caf sd2
 [audiofile] wav au aiff aif
 [dsdiff] dff
 [dsf] dsf
 [hybrid_dsd] m4a
 [faad] aac
 [mpcdec] mpc
 [wavpack] wv
 [modplug] 669 amf ams dbm dfm dsm far it med mdl mod mtm mt2 okt s3m stm ult umx xm
 [mikmod] amf dsm far gdm imf it med mod mtm s3m stm stx ult uni xm
 [sidplay] sid mus str prg P00
 [wildmidi] mid
 [fluidsynth] mid
 [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 adx afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tak tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve rtp:// rtsp:// rtsps://
 [gme] ay gbs gym hes kss nsf nsfe sap spc vgm vgz
 [pcm]

Filters:
 libsamplerate soxr

Tag plugins:
 id3tag

Output plugins:
 shout null fifo pipe alsa ao oss openal solaris pulse jack httpd recorder

Encoder plugins:
 null vorbis opus lame twolame wave flac

Archive plugins:
 [bz2] bz2
 [zzip] zip
 [iso] iso

Input plugins:
 file io_uring archive alsa tidal qobuz curl ffmpeg smbclient nfs mms cdio_paranoia

Playlist plugins:
 extm3u m3u pls xspf asx rss soundcloud flac cue embcue

Protocols:
 file:// alsa:// cdda:// ftp:// ftps:// gopher:// hls+http:// hls+https:// http:// https:// mms:// mmsh:// mmst:// mmsu:// nfs:// qobuz:// rtmp:// rtmpe:// rtmps:// rtmpt:// rtmpte:// rtmpts:// rtp:// rtsp:// rtsps:// scp:// sftp:// smb:// srtp:// tidal://

Other features:
 avahi dbus udisks epoll icu inotify ipv6 systemd tcp un
```

## Log

```
$ mpd --stderr --no-daemon --verbose
config_file: loading file /home/ian/.config/mpd/mpd.conf
exception: bind to '0.0.0.0:6600' failed (continuing anyway, because binding to '[::]:6600' succeeded): Failed to bind socket: Address already in use
path: SetFSCharset: fs charset is:
libsamplerate: libsamplerate converter 'Fastest Sinc Interpolator'
vorbis: Xiph.Org libVorbis 1.3.7
opus: libopus 1.3.1
sndfile: libsndfile-1.0.28
hybrid_dsd: The Hybrid DSD decoder is disabled because it was not explicitly enabled
exception: Decoder plugin 'wildmidi' is unavailable: configuration file does not exist: /etc/timidity/timidity.cfg
simple_db: reading DB
Failed to initialize io_uring: io_uring_queue_init() failed: Cannot allocate memory
exception: Input plugin 'tidal' is not configured: No Tidal application token configured
exception: Input plugin 'qobuz' is not configured: No Qobuz app_id configured
curl: version 7.73.0
curl: with OpenSSL/1.1.1h
avahi: Initializing interface
exception: RTIOThread could not get realtime scheduling, continuing anyway: sched_setscheduler failed: Operation not permitted
avahi: Client changed to state 101
avahi: Client is CONNECTING
state_file: Loading state file /home/ian/.config/mpd/state
inotify: initializing inotify
inotify: watching music directory
client: [0] opened from [::1]:49478
client: [0] process command "status"
client: [0] command returned 0
client: [0] process command "plchanges "0""
client: [0] command returned 0
client: [0] process command "outputs"
client: [0] command returned 0
client: [0] process command "decoders"
client: [0] command returned 0
client: [0] process command "outputs"
client: [0] command returned 0
client: [0] process command "outputs"
client: [0] command returned 0
client: [0] process command "list Artist"
client: [0] command returned 0
client: [0] process command "find Artist "A B & The Sea""
client: [0] command returned 0
client: [0] process command "find Artist "A B & The Sea" Album "Constant Vacation" Date "2012-05-02""
client: [0] command returned 0
client: [0] process command "idle"
client: [0] command returned 1
```

## mpd.conf
```conf
# An example configuration file for MPD.
# Read the user manual for documentation: http://www.musicpd.org/doc/user/
# or /usr/share/doc/mpd/user-manual.html


# Files and directories #######################################################
#
# This setting controls the top directory which MPD will search to discover the
# available audio files and add them to the daemon's online database. This 
# setting defaults to the XDG directory, otherwise the music directory will be
# be disabled and audio files will only be accepted over ipc socket (using
# file:// protocol) or streaming files over an accepted protocol.
#
music_directory		 "~/.config/mpd/music"
#
# This setting sets the MPD internal playlist directory. The purpose of this
# directory is storage for playlists created by MPD. The server will use 
# playlist files not created by the server but only if they are in the MPD
# format. This setting defaults to playlist saving being disabled.
#
playlist_directory "~/.config/mpd/playlists"
#
# This setting sets the location of the MPD database. This file is used to
# load the database at server start up and store the database while the 
# server is not up. This setting defaults to disabled which will allow
# MPD to accept files over ipc socket (using file:// protocol) or streaming
# files over an accepted protocol.
#
db_file            "~/.config/mpd/database"
# 
# These settings are the locations for the daemon log files for the daemon.
# These logs are great for troubleshooting, depending on your log_level
# settings.
#
# The special value "syslog" makes MPD use the local syslog daemon. This
# setting defaults to logging to syslog, otherwise logging is disabled.
#
log_file			     "syslog"
#
# This setting sets the location of the file which stores the process ID
# for use of mpd --kill and some init scripts. This setting is disabled by
# default and the pid file will not be stored.
#
pid_file		       "~/.config/mpd/pid"	
#
# This setting sets the location of the file which contains information about
# most variables to get MPD back into the same general shape it was in before
# it was brought down. This setting is disabled by default and the server 
# state will be reset on server start up.
#
state_file			   "~/.config/mpd/state"
#
# The location of the sticker database.  This is a database which
# manages dynamic information attached to songs.
#
sticker_file       "~/.config/mpd/sticker.sql" 
#
###############################################################################


# General music daemon options ################################################
#
# This setting specifies the user that MPD will run as. MPD should never run as
# root and you may use this setting to make MPD change its user ID after
# initialization. This setting is disabled by default and MPD is run as the
# current user.
#
#user				"mpd"
#
# This setting specifies the group that MPD will run as. If not specified
# primary group of user specified with "user" setting will be used (if set).
# This is useful if MPD needs to be a member of group such as "audio" to
# have permission to use sound card.
#
#group                          "nogroup"
#
# This setting sets the address for the daemon to listen on. Careful attention
# should be paid if this is assigned to anything other then the default, any.
# This setting can deny access to control of the daemon. Choose any if you want
# to have mpd listen on every address. Not effective if systemd socket
# activation is in use.
#
# For network
#bind_to_address		"localhost"
#
# And for Unix Socket
#bind_to_address		"/run/mpd/socket"
#
# This setting is the TCP port that is desired for the daemon to get assigned
# to.
#
port				"6600"
#
# This setting controls the type of information which is logged. Available 
# setting arguments are "default", "secure" or "verbose". The "verbose" setting
# argument is recommended for troubleshooting, though can quickly stretch
# available resources on limited hardware storage.
#
log_level			"default"
#
# If you have a problem with your MP3s ending abruptly it is recommended that 
# you set this argument to "no" to attempt to fix the problem. If this solves
# the problem, it is highly recommended to fix the MP3 files with vbrfix
# (available as vbrfix in the debian archive), at which
# point gapless MP3 playback can be enabled.
#
#gapless_mp3_playback			"yes"
#
# Setting "restore_paused" to "yes" puts MPD into pause mode instead
# of starting playback after startup.
#
#restore_paused "no"
#
# This setting enables MPD to create playlists in a format usable by other
# music players.
#
#save_absolute_paths_in_playlists	"no"
#
# This setting defines a list of tag types that will be extracted during the 
# audio file discovery process. The complete list of possible values can be
# found in the mpd.conf man page.
#metadata_to_use	"artist,album,title,track,name,genre,date,composer,performer,disc"
#
# This setting enables automatic update of MPD's database when files in 
# music_directory are changed.
#
auto_update    "yes"
#
# Limit the depth of the directories being watched, 0 means only watch
# the music directory itself.  There is no limit by default.
#
#auto_update_depth "3"
#
###############################################################################


# Symbolic link behavior ######################################################
#
# If this setting is set to "yes", MPD will discover audio files by following 
# symbolic links outside of the configured music_directory.
#
#follow_outside_symlinks	"yes"
#
# If this setting is set to "yes", MPD will discover audio files by following
# symbolic links inside of the configured music_directory.
#
#follow_inside_symlinks		"yes"
#
###############################################################################


# Zeroconf / Avahi Service Discovery ##########################################
#
# If this setting is set to "yes", service information will be published with
# Zeroconf / Avahi.
#
#zeroconf_enabled		"yes"
#
# The argument to this setting will be the Zeroconf / Avahi unique name for
# this MPD server on the network.
#
#zeroconf_name			"Music Player"
#
###############################################################################


# Permissions #################################################################
#
# If this setting is set, MPD will require password authorization. The password
# can setting can be specified multiple times for different password profiles.
#
#password                        "password@read,add,control,admin"
#
# This setting specifies the permissions a user has who has not yet logged in. 
#
#default_permissions             "read,add,control,admin"
#
###############################################################################
default_permissions             "read,add,control,admin"


# Database #######################################################################
#

#database {
#       plugin "proxy"
#       host "other.mpd.host"
#       port "6600"
#}

# Input #######################################################################
#

input {
        plugin "curl"
#       proxy "proxy.isp.com:8080"
#       proxy_user "user"
#       proxy_password "password"
}

#
###############################################################################

# Audio Output ################################################################
#
# MPD supports various audio output types, as well as playing through multiple 
# audio outputs at the same time, through multiple audio_output settings 
# blocks. Setting this block is optional, though the server will only attempt
# autodetection for one sound card.

audio_output {
    type        "pulse"
    name        "pulse audio"
}


#
# An example of an ALSA output:
#
# audio_output {
# 	type		"alsa"
# 	name		"My ALSA Device"
# #	device		"hw:0,0"	# optional
# #	mixer_type      "hardware"      # optional
# #	mixer_device	"default"	# optional
# #	mixer_control	"PCM"		# optional
# #	mixer_index	"0"		# optional
# }
#
# An example of an OSS output:
#
#audio_output {
#	type		"oss"
#	name		"My OSS Device"
#	device		"/dev/dsp"	# optional
#	mixer_type      "hardware"      # optional
#	mixer_device	"/dev/mixer"	# optional
#	mixer_control	"PCM"		# optional
#}
#
# An example of a shout output (for streaming to Icecast):
#
#audio_output {
#	type		"shout"
#	encoder		"vorbis"		# optional
#	name		"My Shout Stream"
#	host		"localhost"
#	port		"8000"
#	mount		"/mpd.ogg"
#	password	"hackme"
#	quality		"5.0"
#	bitrate		"128"
#	format		"44100:16:1"
#	protocol	"icecast2"		# optional
#	user		"source"		# optional
#	description	"My Stream Description"	# optional
#	url             "http://example.com"    # optional
#	genre		"jazz"			# optional
#	public		"no"			# optional
#	timeout		"2"			# optional
#	mixer_type      "software"              # optional
#}
#
# An example of a recorder output:
#
#audio_output {
#       type            "recorder"
#       name            "My recorder"
#       encoder         "vorbis"                # optional, vorbis or lame
#       path            "/var/lib/mpd/recorder/mpd.ogg"
##      quality         "5.0"                   # do not define if bitrate is defined
#       bitrate         "128"                   # do not define if quality is defined
#       format          "44100:16:1"
#}
#
# An example of a httpd output (built-in HTTP streaming server):
#
#audio_output {
#	type		"httpd"
#	name		"My HTTP Stream"
#	encoder		"vorbis"		# optional, vorbis or lame
#	port		"8000"
#	bind_to_address "0.0.0.0"               # optional, IPv4 or IPv6
#	quality		"5.0"			# do not define if bitrate is defined
#	bitrate		"128"			# do not define if quality is defined
#	format		"44100:16:1"
#	max_clients     "0"                     # optional 0=no limit
#}
#
# An example of a pulseaudio output (streaming to a remote pulseaudio server)
# Please see README.Debian if you want mpd to play through the pulseaudio
# daemon started as part of your graphical desktop session!
#
#audio_output {
#	type		"pulse"
#	name		"My Pulse Output"
#	server		"remote_server"		# optional
#	sink		"remote_server_sink"	# optional
#}
#
# An example of a winmm output (Windows multimedia API).
#
#audio_output {
#	type		"winmm"
#	name		"My WinMM output"
#	device		"Digital Audio (S/PDIF) (High Definition Audio Device)" # optional
#		or
#	device		"0"		# optional
#	mixer_type	"hardware"	# optional
#}
#
# An example of an openal output.
#
#audio_output {
#	type		"openal"
#	name		"My OpenAL output"
#	device		"Digital Audio (S/PDIF) (High Definition Audio Device)" # optional
#}
#
# An example of an sndio output.
#
#audio_output {
#  type        "sndio"
#  name        "sndio output"
#  mixer_type  "software"
#}
#
## Example "pipe" output:
#
#audio_output {
#	type		"pipe"
#	name		"my pipe"
#	command		"aplay -f cd 2>/dev/null"
## Or if you're want to use AudioCompress
#	command		"AudioCompress -m | aplay -f cd 2>/dev/null"
## Or to send raw PCM stream through PCM:
#	command		"nc example.org 8765"
#	format		"44100:16:2"
#}
#
## An example of a null output (for no audio output):
#
#audio_output {
#	type		"null"
#	name		"My Null Output"
#	mixer_type      "none"                  # optional
#}
#
###############################################################################


# Normalization automatic volume adjustments ##################################
#
# This setting specifies the type of ReplayGain to use. This setting can have
# the argument "off", "album", "track" or "auto". "auto" is a special mode that
# chooses between "track" and "album" depending on the current state of
# random playback. If random playback is enabled then "track" mode is used.
# See <http://www.replaygain.org> for more details about ReplayGain.
# This setting is off by default.
#
#replaygain			"album"
#
# This setting sets the pre-amp used for files that have ReplayGain tags. By
# default this setting is disabled.
#
#replaygain_preamp		"0"
#
# This setting sets the pre-amp used for files that do NOT have ReplayGain tags.
# By default this setting is disabled.
#
#replaygain_missing_preamp	"0"
#
# This setting enables or disables ReplayGain limiting.
# MPD calculates actual amplification based on the ReplayGain tags
# and replaygain_preamp / replaygain_missing_preamp setting.
# If replaygain_limit is enabled MPD will never amplify audio signal
# above its original level. If replaygain_limit is disabled such amplification
# might occur. By default this setting is enabled.
#
#replaygain_limit		"yes"
#
# This setting enables on-the-fly normalization volume adjustment. This will
# result in the volume of all playing audio to be adjusted so the output has 
# equal "loudness". This setting is disabled by default.
#
#volume_normalization		"no"
#
###############################################################################


# Character Encoding ##########################################################
#
# If file or directory names do not display correctly for your locale then you 
# may need to modify this setting.
#
filesystem_charset		"UTF-8"
#
###############################################################################

max_output_buffer_size "20480"

```

## Other info

```bash
# File permission on state file
$ ls -l ~/.config/mpd/state
-rw-r--r-- 1 ian ian 0 Oct 22 21:24 /home/ian/.config/mpd/state

# Obviously haven't run out of system memory
$ free -m
              total        used        free      shared  buff/cache   available
Mem:          15899        2472        7097         992        6329       12104
Swap:          511

# Memory limits on mpd process
$ cat /proc/$(pidof mpd)/limits
Limit                     Soft Limit           Hard Limit           Units
Max cpu time              unlimited            unlimited            seconds
Max file size             unlimited            unlimited            bytes
Max data size             unlimited            unlimited            bytes
Max stack size            8388608              unlimited            bytes
Max core file size        unlimited            unlimited            bytes
Max resident set          unlimited            unlimited            bytes
Max processes             63523                63523                processes
Max open files            1024                 524288               files
Max locked memory         65536                65536                bytes
Max address space         unlimited            unlimited            bytes
Max file locks            unlimited            unlimited            locks
Max pending signals       63523                63523                signals
Max msgqueue size         819200               819200               bytes
Max nice priority         0                    0
Max realtime priority     0                    0
Max realtime timeout      unlimited            unlimited            us

# Increasing "max locked memory" to 512 MiB didn't help
sudo prlimit --pid $(pidof mpd) --memlock=536870912:536870912
$ cat /proc/$(pidof mpd)/limits | grep lock
Max locked memory         536870912            536870912            bytes
Max file locks            unlimited            unlimited            locks
```

**Comment by leigh123linux** [comment] 2020-10-23 04:36
See https://github.com/MusicPlayerDaemon/MPD/commit/27cc7b352d54b013e04c6e2b66b7ff0ab6e6bfb8

The default is 2 minutes, try adding this to your conf

```
 state_file_interval               "1"
```

**Comment by MaxKellermann** [comment] 2020-10-23 07:04
@leigh123linux good point, but MPD *should* save the state file on proper shutdown.

@ian-s-mcb why do you believe this is related to io_uring? Your log is incomplete, it doesn't show a restart of MPD.

**Comment by leigh123linux** [comment] 2020-10-23 08:53
@MaxKellermann 

It doesn't here if I update the package  which runs this scriplet to restart mpd

https://pkgs.rpmfusion.org/cgit/free/mpd.git/tree/mpd.spec#n210

**Comment by MaxKellermann** [comment] 2020-10-23 08:54
> It doesn't here if I update the package which runs this scriplet to restart mpd

So that's the problem, I guess, and this has nothing to do with io_uring at all.

**Comment by ian-s-mcb** [comment] 2020-10-23 17:35
@MaxKellermann Below is a log that included a restart of MPD. 

@leigh123linux Adding `state_file_interval "1"` to my mpd.conf fixed the state issue.

The io_uring error is still being thrown. Should I ignore it?

## Log with add tracks, service restart, and empty playlist

```
$ mpd --stderr --no-daemon --verbose
config_file: loading file /home/ian/.config/mpd/mpd.conf
exception: bind to '0.0.0.0:6600' failed (continuing anyway, because binding to '[::]:6600' succeeded): Failed to bind socket: Address already in use
path: SetFSCharset: fs charset is:
libsamplerate: libsamplerate converter 'Fastest Sinc Interpolator'
vorbis: Xiph.Org libVorbis 1.3.7
opus: libopus 1.3.1
sndfile: libsndfile-1.0.28
hybrid_dsd: The Hybrid DSD decoder is disabled because it was not explicitly enabled
exception: Decoder plugin 'wildmidi' is unavailable: configuration file does not exist: /etc/timidity/timidity.cfg
simple_db: reading DB
Failed to initialize io_uring: io_uring_queue_init() failed: Cannot allocate memory
exception: Input plugin 'tidal' is not configured: No Tidal application token configured
exception: Input plugin 'qobuz' is not configured: No Qobuz app_id configured
curl: version 7.73.0
curl: with OpenSSL/1.1.1h
avahi: Initializing interface
exception: RTIOThread could not get realtime scheduling, continuing anyway: sched_setscheduler failed: Operation not permitted
avahi: Client changed to state 101
avahi: Client is CONNECTING
state_file: Loading state file /home/ian/.config/mpd/state
inotify: initializing inotify
inotify: watching music directory
client: [0] opened from [::1]:60416
client: [0] process command "status"
client: [0] command returned 0
client: [0] process command "plchanges "0""
client: [0] command returned 0
client: [0] process command "outputs"
client: [0] command returned 0
client: [0] process command "decoders"
client: [0] command returned 0
client: [0] process command "outputs"
client: [0] command returned 0
client: [0] process command "outputs"
client: [0] command returned 0
client: [0] process command "idle"
client: [0] command returned 1
client: [0] process command "list Artist"
client: [0] command returned 0
client: [0] process command "find Artist "[unknown]""
client: [0] command returned 0
client: [0] process command "find Artist "[unknown]" Album "20 Years of Dischord" Date "2002-10-15""
client: [0] command returned 0
client: [0] process command "idle"
client: [0] command returned 1
client: [0] process command "find Artist "Air""
client: [0] command returned 0
client: [0] process command "find Artist "Air" Album "Playground Love" Date "2000-01-17""
client: [0] command returned 0
client: [0] process command "idle"
client: [0] command returned 1
client: [0] process command "find Artist "Air""
client: [0] command returned 0
client: [0] process command "addid "music-full/Air/2000 - Playground Love/03 Playground Love (Vibraphone version).mp3""
client: [0] command returned 0
client: [0] process command "addid "music-full/Air/2007 - Pocket Symphony/01 Space Maker.mp3""
client: [0] command returned 0
client: [0] process command "addid "music-full/Air/2007 - Pocket Symphony/02 Once Upon a Time.mp3""
client: [0] command returned 0
client: [0] process command "addid "music-full/Air/2007 - Pocket Symphony/03 One Hell of a Party.mp3""
client: [0] command returned 0
client: [0] process command "addid "music-full/Air/2007 - Pocket Symphony/04 Napalm Love.mp3""
client: [0] command returned 0
client: [0] process command "addid "music-full/Air/2007 - Pocket Symphony/05 Mayfair Song.mp3""
client: [0] command returned 0
client: [0] process command "addid "music-full/Air/2007 - Pocket Symphony/06 Left Bank.mp3""
client: [0] command returned 0
client: [0] process command "addid "music-full/Air/2007 - Pocket Symphony/07 Photograph.mp3""
client: [0] command returned 0
client: [0] process command "addid "music-full/Air/2007 - Pocket Symphony/08 Mer du Japon.mp3""
client: [0] command returned 0
client: [0] process command "addid "music-full/Air/2007 - Pocket Symphony/09 Lost Message.mp3""
client: [0] command returned 0
client: [0] process command "addid "music-full/Air/2007 - Pocket Symphony/10 Somewhere Between Waking and Sleeping.mp3""
client: [0] command returned 0
client: [0] process command "addid "music-full/Air/2007 - Pocket Symphony/11 Redhead Girl.mp3""
client: [0] command returned 0
client: [0] process command "addid "music-full/Air/2007 - Pocket Symphony/12 Night Sight.mp3""
client: [0] command returned 0
client: [0] process command "idle"
client: [0] command returned 1
client: [0] process command "status"
client: [0] command returned 0
client: [0] process command "plchanges "1""
client: [0] command returned 0
client: [0] process command "idle"
client: [0] command returned 1
client: [0] process command "find Artist "Airhead""
client: [0] command returned 0
client: [0] process command "find Artist "Airhead" Album "LateNightTales: Bonobo" Date "2013-11-18""
client: [0] command returned 0
client: [0] process command "idle"
client: [0] command returned 1
^Cavahi: Shutting down interface
mpd: ../src/event/Loop.cxx:70: EventLoop::~EventLoop(): Assertion `sockets.empty()' failed.
Aborted (core dumped)

$ mpd --stderr --no-daemon --verbose
config_file: loading file /home/ian/.config/mpd/mpd.conf
exception: bind to '0.0.0.0:6600' failed (continuing anyway, because binding to '[::]:6600' succeeded): Failed to bind socket: Address already in use
path: SetFSCharset: fs charset is:
libsamplerate: libsamplerate converter 'Fastest Sinc Interpolator'
vorbis: Xiph.Org libVorbis 1.3.7
opus: libopus 1.3.1
sndfile: libsndfile-1.0.28
hybrid_dsd: The Hybrid DSD decoder is disabled because it was not explicitly enabled
exception: Decoder plugin 'wildmidi' is unavailable: configuration file does not exist: /etc/timidity/timidity.cfg
simple_db: reading DB
Failed to initialize io_uring: io_uring_queue_init() failed: Cannot allocate memory
exception: Input plugin 'tidal' is not configured: No Tidal application token configured
exception: Input plugin 'qobuz' is not configured: No Qobuz app_id configured
curl: version 7.73.0
curl: with OpenSSL/1.1.1h
avahi: Initializing interface
exception: RTIOThread could not get realtime scheduling, continuing anyway: sched_setscheduler failed: Operation not permitted
avahi: Client changed to state 101
avahi: Client is CONNECTING
state_file: Loading state file /home/ian/.config/mpd/state
inotify: initializing inotify
inotify: watching music directory
client: [0] opened from [::1]:60446
client: [0] process command "status"
client: [0] command returned 0
client: [0] process command "plchanges "0""
client: [0] command returned 0
client: [0] process command "outputs"
client: [0] command returned 0
client: [0] process command "decoders"
client: [0] command returned 0
client: [0] process command "outputs"
client: [0] command returned 0
client: [0] process command "outputs"
client: [0] command returned 0
client: [0] process command "idle"
client: [0] command returned 1
```

**Comment by MaxKellermann** [comment] 2020-10-23 17:43
Of course MPD can't write the state file on shutdown. It crashes before it gets a chance to do that!
Duplicate of https://github.com/MusicPlayerDaemon/MPD/issues/986
About the io_uring error see https://www.musicpd.org/doc/html/user.html#error-failed-to-initialize-io-uring

**Closed by MaxKellermann** 2020-10-23 17:43 UTC

**Comment by ian-s-mcb** [comment] 2020-10-23 17:56
I don't understand why you marked this as a duplicate of #986 .

I noticed the MPD crash, but only on when I installed MPD from source in order to get an unstripped binary:

$ mpd --version
Music Player Daemon 0.23~git (v0.22.1-67-gad585e179+)

When I installed MPD from the Arch Linux package, the service shuts down without an error:

$ mpd  --version
Music Player Daemon 0.22.1 (0.22.1)
