### ISSUE TITLE
error: call to non-constexpr function ‘const _Tp& std::max

### ISSUE THREAD

**Issue by norrest** [MusicPlayerDaemon/MPD#48] opened 2017-05-19 06:30 UTC
Wshadow -Wpointer-arith -Wcast-qual -Wwrite-strings -Wsign-compare -MT src/output/libmpd_a-Source.o -MD -MP -MF src/output/.deps/libmpd_a-Source.Tpo -c -o src/output/libmpd_a-Source.o `test -f 'src/output/Source.cxx' || echo './'`src/output/Source.cxx
src/Main.cxx:129:23: error: call to non-constexpr function ‘const _Tp& std::max(const _Tp&, const _Tp&) [with _Tp = unsigned int]’
          64 * KILOBYTE);
                       ^
Makefile:14264: recipe for target 'src/Main.o' failed
make[1]: *** [src/Main.o] Error 1
make[1]: *** Waiting for unfinished jobs....
-----------------------------------------------------
mpd ver 
http://www.musicpd.org/download/mpd/0.20/mpd-0.20.7.tar.xz

**Comment by norrest** [comment] 2017-05-19 08:50
Previously mpd-0.20.6 - ok!

**Comment by MaxKellermann** [comment] 2017-05-19 17:18
Duplicate of https://github.com/MusicPlayerDaemon/MPD/issues/45

**Closed by MaxKellermann** 2017-05-19 17:18 UTC
