### ISSUE TITLE
Process dumped to core (Archlinux, mpd.service --user)

### ISSUE THREAD

**Issue by Utini2000** [MusicPlayerDaemon/MPD#984] opened 2020-10-21 12:55 UTC
### Describe the bug
When starting mpd.service --user it crashes and won't start.

## Expected Behavior
Start correctly

## Actual Behavior
Not starting

## Version
```
 Music Player Daemon 0.22 (0.22)
Copyright 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2018 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple proxy upnp

Storage plugins:
 local smbclient udisks nfs curl

Neighbor plugins:
 smbclient upnp udisks

Decoders plugins:
 [mad] mp3 mp2
 [mpg123] mp3
 [vorbis] ogg oga
 [oggflac] ogg oga
 [flac] flac
 [opus] opus ogg oga
 [sndfile] wav aiff aif au snd paf iff svx sf voc w64 pvf xi htk caf sd2
 [audiofile] wav au aiff aif
 [dsdiff] dff
 [dsf] dsf
 [hybrid_dsd] m4a
 [faad] aac
 [mpcdec] mpc
 [wavpack] wv
 [modplug] 669 amf ams dbm dfm dsm far it med mdl mod mtm mt2 okt s3m stm ult umx xm
 [mikmod] amf dsm far gdm imf it med mod mtm s3m stm stx ult uni xm
 [sidplay] sid mus str prg P00
 [wildmidi] mid
 [fluidsynth] mid
 [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 adx afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tak tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve rtp:// rtsp:// rtsps://
 [gme] ay gbs gym hes kss nsf nsfe sap spc vgm vgz
 [pcm]

Filters:
 libsamplerate soxr

Tag plugins:
 id3tag

Output plugins:
 shout null fifo pipe alsa ao oss openal solaris pulse jack httpd recorder

Encoder plugins:
 null vorbis opus lame twolame wave flac

Archive plugins:
 [bz2] bz2
 [zzip] zip
 [iso] iso

Input plugins:
 file io_uring archive alsa tidal qobuz curl ffmpeg smbclient nfs mms cdio_paranoia

Playlist plugins:
 extm3u m3u pls xspf asx rss soundcloud flac cue embcue

Protocols:
 file:// alsa:// cdda:// ftp:// ftps:// gopher:// hls+http:// hls+https:// http:// https:// mms:// mmsh:// mmst:// mmsu:// nfs:// qobuz:// rtmp:// rtmpe:// rtmps:// rtmpt:// rtmpte:// rtmpts:// rtp:// rtsp:// rtsps:// scp:// sftp:// smb:// srtp:// tidal://

Other features:
 avahi dbus udisks epoll icu inotify ipv6 systemd tcp un
```

## Log
```
mpd.service - Music Player Daemon
     Loaded: loaded (/usr/lib/systemd/user/mpd.service; enabled; vendor preset: enabled)
     Active: failed (Result: signal) since Wed 2020-10-21 14:45:03 CEST; 3s ago
       Docs: man:mpd(1)
             man:mpd.conf(5)
    Process: 1299 ExecStart=/usr/bin/mpd --no-daemon (code=killed, signal=SEGV)
   Main PID: 1299 (code=killed, signal=SEGV)

Okt 21 14:44:58 S2000 systemd[1292]: Starting Music Player Daemon...
Okt 21 14:44:58 S2000 mpd[1299]: Oct 21 14:44 : exception: Tag list mismatch, discarding database file
Okt 21 14:44:59 S2000 systemd[1292]: Started Music Player Daemon.
Okt 21 14:45:03 S2000 systemd[1292]: mpd.service: Main process exited, code=killed, status=11/SEGV
Okt 21 14:45:03 S2000 systemd[1292]: mpd.service: Failed with result 'signal'.
Okt 21 14:45:03 S2000 systemd-coredump[1634]: Process 1299 (mpd) of user 1000 dumped core.
                                              
                                              Stack trace of thread 1326:
                                              #0  0x000005786391ca81 n/a (mpd + 0xe0a81)
                                              #1  0x000005786391d050 n/a (mpd + 0xe1050)
                                              #2  0x000005786392290a n/a (mpd + 0xe690a)
                                              #3  0x00000578639236f4 n/a (mpd + 0xe76f4)
                                              #4  0x0000057863921793 n/a (mpd + 0xe5793)
                                              #5  0x00000578639236f4 n/a (mpd + 0xe76f4)
                                              #6  0x0000057863921793 n/a (mpd + 0xe5793)
                                              #7  0x00000578639236f4 n/a (mpd + 0xe76f4)
                                              #8  0x0000057863921793 n/a (mpd + 0xe5793)
                                              #9  0x00000578639236f4 n/a (mpd + 0xe76f4)
                                              #10 0x000005786391a3f3 n/a (mpd + 0xde3f3)
                                              #11 0x00000578638b86a4 n/a (mpd + 0x7c6a4)
                                              #12 0x00006d355a3993e9 start_thread (libpthread.so.0 + 0x93e9)
                                              #13 0x00006d3558132293 __clone (libc.so.6 + 0x100293)
                                              
                                              Stack trace of thread 1325:
                                              #0  0x00006d35581325de epoll_wait (libc.so.6 + 0x1005de)
                                              #1  0x00000578638bebf6 n/a (mpd + 0x82bf6)
                                              #2  0x00000578638b86a4 n/a (mpd + 0x7c6a4)
                                              #3  0x00006d355a3993e9 start_thread (libpthread.so.0 + 0x93e9)
                                              #4  0x00006d3558132293 __clone (libc.so.6 + 0x100293)
                                              
                                              Stack trace of thread 1299:
                                              #0  0x00006d35581325de epoll_wait (libc.so.6 + 0x1005de)
                                              #1  0x00000578638bebf6 n/a (mpd + 0x82bf6)
                                              #2  0x000005786388cfd1 n/a (mpd + 0x50fd1)
                                              #3  0x000005786388e18d n/a (mpd + 0x5218d)
                                              #4  0x000005786388441c n/a (mpd + 0x4841c)
                                              #5  0x00006d355805a152 __libc_start_main (libc.so.6 + 0x28152)
                                              #6  0x000005786388471e n/a (mpd + 0x4871e)
                                              
                                              Stack trace of thread 1324:
                                              #0  0x00006d35581325de epoll_wait (libc.so.6 + 0x1005de)
                                              #1  0x00000578638bebf6 n/a (mpd + 0x82bf6)
                                              #2  0x00000578638b86a4 n/a (mpd + 0x7c6a4)
                                              #3  0x00006d355a3993e9 start_thread (libpthread.so.0 + 0x93e9)
                                              #4  0x00006d3558132293 __clone (libc.so.6 + 0x100293)


------------------- from the log file:
Oct 21 14:52 : ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: stream 0, timescale not set
Oct 21 14:51 : ffmpeg/flac: Format flac detected only with low score of 1, misdetection possible!
Oct 21 14:51 : ffmpeg/flac: Could not find codec parameters for stream 0 (Audio: flac, 0 channels): unspecified sample format
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Oct 21 14:51 : ffmpeg: Unsupported libavcodec SampleFormat value: name   depth (-1)

```

## Config file /home/user/.config/mpd/mpd.conf  

```
music_directory         "~/Music"
playlist_directory              "~/Music/Playlists"
db_file            "~/.config/mpd/database"
log_file                        "~/.config/mpd/log"
pid_file                        "~/.config/mpd/pid"
state_file                      "~/.config/mpd/state"
sticker_file                    "~/.config/mpd/sticker.sql"
#bind_to_address                "any"
bind_to_address                 "0.0.0.0"
#bind_to_address                        "127.0.0.1"
port                            "6660"
restore_paused "yes"
auto_update     "yes"
zeroconf_enabled                "no"
password "not pasting here"

audio_output {
        type            "alsa"
        name            "ALSA Bit Perfect"
        device          "hw:1,0"        # optional
        mixer_type      "disabled"      # optional
}

audio_output {
        type            "pulse"
        name            "My Pulse Output"
##      server          "remote_server"         # optional
##      sink            "remote_server_sink"    # optional
        server          "127.0.0.1"
#    mixer_type "software"      # optional
#    mixer_control      "PCM"   # optional
}


replaygain                      "auto"

 ```

**Comment by Utini2000** [comment] 2020-10-21 12:55
I hope you can read the version/log/config file? 
It is included in the post (e.g. when I edit it) but not shown for some reason?

**Comment by MaxKellermann** [comment] 2020-10-21 13:01
You made your paste invisible by leaving the comment syntax in.

Your backtrace is useless because your MPD executable is stripped. I need a backtrace with debug info.

**Comment by Utini2000** [comment] 2020-10-21 13:26
@MaxKellermann yes sorry. I re-ran with "verbose" logging. I hope this is correct?

The log is too big to paste here and will crash any paste-services. I uploaded it to my webserver:
https://files.bestmail.ws/mpd-verbose.log

**Comment by MaxKellermann** [comment] 2020-10-21 13:33
Duplicate of https://github.com/MusicPlayerDaemon/MPD/issues/974
Hey, why are you reporting bugs for an outdated version?

**Closed by MaxKellermann** 2020-10-21 13:33 UTC
