### ISSUE TITLE
can not start

### ISSUE THREAD

**Issue by zhouguannan** [MusicPlayerDaemon/MPD#1145] opened 2021-04-25 03:29 UTC
### Describe the bug
"Permission denied"
 when I "sudo systemctl restart mpd"
## config
audio_output {
    type        "pulse"
    name        "My Pulse Output"
    server        "127.0.0.1"
}
audio_output {
    type                    "fifo"
    name                    "my_fifo"
    path                    "/tmp/mpd.fifo"
    format                  "44100:16:2"
}
pid_file "/run/mpd/mpd.pid"
db_file "/var/lib/mpd/mpd.db"
state_file "/var/lib/mpd/mpdstate"
playlist_directory "/var/lib/mpd/playlists"
music_directory "/home/kevin/Music/"
filesystem_charset              "UTF-8"
## Version
Music Player Daemon 0.23~git (v0.22.6-473-g423f2df5e+)
## Log

Apr 25 10:34:52 ArchLinux systemd[1]: Stopping Music Player Daemon...
Apr 25 11:24:28 ArchLinux mpd[382241]: exception: Failed to access /var/lib/mpd/playlists: Permission denied
Apr 25 11:24:28 ArchLinux mpd[382241]: exception: Decoder plugin 'wildmidi' is unavailable: configuration file does not exist: /etc/timidity/timidity.cfg
Apr 25 11:24:28 ArchLinux mpd[382241]: exception: Failed to access /home/kevin/Music: Permission denied
Apr 25 11:24:28 ArchLinux mpd[382241]: exception: Failed to open '/var/lib/mpd/mpd.db': Permission denied
Apr 25 11:24:28 ArchLinux mpd[382241]: exception: Failed to open database plugin; Can't create db file in "/var/lib/mpd": Permission denied
Apr 25 11:24:28 ArchLinux systemd[1]: mpd.service: Main process exited, code=exited, status=1/FAILURE

**Comment by MaxKellermann** [comment] 2021-04-25 07:47
Duplicate of your own report https://github.com/MusicPlayerDaemon/MPD/issues/1144
Please don't repeat your bug reports when I have already explained that it was bogus.

**Closed by MaxKellermann** 2021-04-25 07:47 UTC
