### ISSUE TITLE
Customize cover file name prefix

### ISSUE THREAD

**Issue by mistepien** [MusicPlayerDaemon/MPD#650] opened 2019-09-17 08:43 UTC
## Feature request
Now mpd will send to client "cover.png, cover.jpg, cover.tiff or cover.bmp" cover files. It would be great to have an option in mpd.conf to customize the prefix of cover file and be able to use eg. folder.jpg, folder.tiff and so on.

**Comment by MaxKellermann** [comment] 2019-09-20 15:54
Duplicate of https://github.com/MusicPlayerDaemon/MPD/issues/301

**Closed by MaxKellermann** 2019-09-20 15:54 UTC
