### ISSUE TITLE
Authentication broken

### ISSUE THREAD

**Issue by MeindertKempe** [MusicPlayerDaemon/MPD#1282] opened 2021-10-16 01:37 UTC
### Describe the bug
In mpd version 0.23 authentication seems entirely broken, trying to connect with a password gives no permissions and connecting from localhost only `default_permissions` are given.

Relevant config:
```
# Permissions #################################################################
#
# If this setting is set, MPD will require password authorization. The password
# setting can be specified multiple times for different password profiles.
#
password                       "password@read,add,player,control,admin"
#
# This setting specifies the permissions a user has who has not yet logged in. 
#
default_permissions       "read"
#
local_permissions          "read,add,player,control,admin"
###############################################################################
```

## Expected Behavior
running 
`mpc --host=password@localhost status`
returns the status

running
`mpc --host=localhost status`
returns status

running
`mpc --host=localhost play`
starts playing

## Actual Behavior
running 
`mpc --host=password@localhost status` 
returns 
`MPD error: you don't have permission for "status"`

running
`mpc --host=localhost status`
returns status

running
`mpc --host=localhost play`
returns
`MPD error: you don't have permission for "play"`

## Version

```
Music Player Daemon 0.23 (0.23)
Copyright 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2021 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple proxy upnp

Storage plugins:
 local udisks nfs curl

Neighbor plugins:
 upnp udisks

Decoders plugins:
 [mad] mp3 mp2
 [mpg123] mp3
 [vorbis] ogg oga
 [oggflac] ogg oga
 [flac] flac
 [opus] opus ogg oga
 [sndfile] wav aiff aif au snd paf iff svx sf voc w64 pvf xi htk caf sd2
 [audiofile] wav au aiff aif
 [dsdiff] dff
 [dsf] dsf
 [hybrid_dsd] m4a
 [faad] aac
 [mpcdec] mpc
 [wavpack] wv
 [openmpt] mptm mod s3m xm it 669 amf ams c67 dbm digi dmf dsm dtm far imf ice j2b m15 mdl med mms mt2 mtm nst okt plm psm pt36 ptm sfx sfx2 st26 stk stm stp ult wow gdm mo3 oxm umx xpk ppm mmcmp
 [modplug] 669 amf ams dbm dfm dsm far it med mdl mod mtm mt2 okt s3m stm ult umx xm
 [mikmod] amf dsm far gdm imf it med mod mtm s3m stm stx ult uni xm
 [sidplay] sid mus str prg P00
 [wildmidi] mid
 [fluidsynth] mid
 [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 adx afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tak tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve rtp:// rtsp:// rtsps://
 [gme] ay gbs gym hes kss nsf nsfe rsn sap spc vgm vgz
 [pcm]

Filters:
 libsamplerate soxr

Tag plugins:
 id3tag

Output plugins:
 shout null fifo pipe alsa ao oss openal solaris pipewire pulse jack httpd snapcast recorder

Encoder plugins:
 null vorbis opus lame twolame wave flac

Archive plugins:
 [bz2] bz2
 [zzip] zip
 [iso] iso

Input plugins:
 file io_uring archive alsa qobuz curl ffmpeg nfs mms cdio_paranoia

Playlist plugins:
 extm3u m3u pls xspf asx rss soundcloud flac cue embcue

Protocols:
 file:// alsa:// cdda:// ftp:// ftps:// gopher:// hls+http:// hls+https:// http:// https:// mms:// mmsh:// mmst:// mmsu:// nfs:// qobuz:// rtmp:// rtmpe:// rtmps:// rtmpt:// rtmpte:// rtmpts:// rtp:// rtsp:// rtsps:// scp:// sftp:// smb:// srtp://

Other features:
 avahi dbus udisks epoll icu inotify ipv6 systemd tcp un
```

## Log
```
Oct 16 03:27:56 mkdesktop mpd[119530]: client: [1] closed
Oct 16 03:27:56 mkdesktop mpd[119530]: client: [1] process command list returned 0
Oct 16 03:27:56 mkdesktop mpd[119530]: client: command returned 0
Oct 16 03:27:56 mkdesktop mpd[119530]: client: process command "currentsong"
Oct 16 03:27:56 mkdesktop mpd[119530]: client: command returned 0
Oct 16 03:27:56 mkdesktop mpd[119530]: client: process command "status"
Oct 16 03:27:56 mkdesktop mpd[119530]: client: [1] process command list
Oct 16 03:27:56 mkdesktop mpd[119530]: client: [1] opened from [::1]:49964
Oct 16 03:27:52 mkdesktop mpd[119530]: client: [0] closed
Oct 16 03:27:52 mkdesktop mpd[119530]: client: [0] process command list returned 3
Oct 16 03:27:52 mkdesktop mpd[119530]: client: command returned 3
Oct 16 03:27:52 mkdesktop mpd[119530]: client: process command "status"
Oct 16 03:27:52 mkdesktop mpd[119530]: client: [0] process command list
Oct 16 03:27:52 mkdesktop mpd[119530]: client: [0] command returned 0
Oct 16 03:27:52 mkdesktop mpd[119530]: client: [0] process command "password "password""
Oct 16 03:27:52 mkdesktop mpd[119530]: client: [0] opened from [::1]:49962
Oct 16 03:27:36 mkdesktop mpd[119530]: output: converting in=44100:24:2 -> f=44100:24:2 -> out=44100:16:2
Oct 16 03:27:36 mkdesktop mpd[119530]: output: opened "my_fifo" (fifo) audio_format=44100:16:2
Oct 16 03:27:36 mkdesktop mpd[119530]: output: OutputThread could not get realtime scheduling, continuing anyway: %s
Oct 16 03:27:36 mkdesktop mpd[119530]: output: opened "pulse audio" (pulse) audio_format=44100:24:2
Oct 16 03:27:36 mkdesktop mpd[119530]: decoder: audio_format=44100:24:2, seekable=true
Oct 16 03:27:36 mkdesktop systemd[587]: Started Music Player Daemon.
Oct 16 03:27:36 mkdesktop mpd[119530]: decoder_thread: probing plugin mad
Oct 16 03:27:36 mkdesktop mpd[119530]: output: OutputThread could not get realtime scheduling, continuing anyway: %s
Oct 16 03:27:36 mkdesktop mpd[119530]: playlist: queue song 0:"The Irish Rovers/01 - Albums/2020 - Saints And Sinners/15 - The Irish Reggae Band.mp3"
Oct 16 03:27:36 mkdesktop mpd[119530]: event: RTIOThread could not get realtime scheduling, continuing anyway: %s
Oct 16 03:27:36 mkdesktop mpd[119530]: state_file: Loading state file /home/mk/.config/mpd/state
Oct 16 03:27:36 mkdesktop mpd[119530]: curl: with OpenSSL/1.1.1l
Oct 16 03:27:36 mkdesktop mpd[119530]: curl: version 7.79.1
Oct 16 03:27:36 mkdesktop mpd[119530]: input: Input plugin 'qobuz' is not configured: %s
Oct 16 03:27:36 mkdesktop mpd[119530]: simple_db: reading DB
Oct 16 03:27:36 mkdesktop mpd[119530]: decoder: Decoder plugin 'wildmidi' is unavailable: configuration file does not exist: /etc/timidity/timidity.cfg
Oct 16 03:27:36 mkdesktop mpd[119530]: hybrid_dsd: The Hybrid DSD decoder is disabled because it was not explicitly enabled
Oct 16 03:27:36 mkdesktop mpd[119530]: sndfile: libsndfile-1.0.31
Oct 16 03:27:36 mkdesktop mpd[119530]: opus: libopus 1.3.1
Oct 16 03:27:36 mkdesktop mpd[119530]: vorbis: Xiph.Org libVorbis 1.3.7
Oct 16 03:27:36 mkdesktop mpd[119530]: libsamplerate: libsamplerate converter 'Fastest Sinc Interpolator'
Oct 16 03:27:36 mkdesktop mpd[119530]: server_socket: bind to '0.0.0.0:6600' failed (continuing anyway, because binding to '[::]:6600' succeeded): Failed to bind socket: Address already in use
Oct 16 03:27:36 mkdesktop systemd[587]: Starting Music Player Daemon...
```

**Comment by morganmay** [comment] 2021-10-16 09:52
I am having the same problem after upgrading from `0.22.11` to `0.23`.

**Comment by MaxKellermann** [comment] 2021-10-17 06:09
First of all, the log you posted does not reflect your description. It does not show a failed `status`. Please post a new log.

> connecting from localhost only `default_permissions` are given.

Of course. Why would localhost be special? Are you mixing up "regular TCP connection from loopback device" (what you're doing) with ["clients connecting on a local socket"](https://mpd.readthedocs.io/en/stable/user.html#permissions-and-passwords) (what `local_permissions` is defined for)?

(A "local socket" is sometimes called ["UNIX domain socket"](https://en.wikipedia.org/wiki/Unix_domain_socket), and is a special kind of connection without TCP and without a network device.)

I doubt that this ever worked for you.

> ## Expected Behavior
> running 
> `mpc --host=password@localhost status`
> returns the status

I tried with your configuration, and this actually returns the status.

> running
> `mpc --host=localhost status`
> returns status

And this worked for me, too.

> running
> `mpc --host=localhost play`
> starts playing

This does not work, by design, as I explained above.

The only thing that's really broken for you is the "No permission for status" with password. Works for me. What you can do is do a `git bisect`, that's the only thing that appears useful to me.

And I'm really curious about the "localhost" problem. Please bisect that as well - what was the most recent commit that still worked? As I said, I doubt this has ever worked, and I think this bug report is wrong, but maybe you can prove me wrong.

**Comment by MaxKellermann** [comment] 2021-10-17 06:43
@justin-sleep, please bisect (works for me, sigh)

**Comment by justin-sleep** [comment] 2021-10-17 07:19
After investigating further, I think this might just be a problem with Arch's package for 0.23. I can't reproduce this with the source code, even when [using the same files and build configuration](https://github.com/archlinux/svntogit-packages/blob/packages/mpd/trunk/PKGBUILD) as Arch's package.

**Comment by MaxKellermann** [comment] 2021-10-17 08:55
Hm, I wonder how a distribution can break their MPD package - what's causing this bug?
In case anybody wants to report another bug: the Arch package has left debugging enabled - release builds should configure with `-Db_ndebug=true`.
I'm closing this bug - we can reopen this if it turns out that this Arch bug is really caused by a MPD bug.

**Comment by MaxKellermann** [comment] 2021-10-17 15:06
Thanks @tryone144, that was the right hint - there's a misplaced `pure` attribute:
https://github.com/MusicPlayerDaemon/MPD/blob/771c46032f4dd60097d46524ef6873a49b051a01/src/Permission.hxx#L35-L37
This breaks because the function has an output parameter, which is a side effect. Of course, output parameters are a bad design, and should be replaced with a `std::optional<unsigned>` return type.
Anybody up to writing a PR for this?

**Closed** 2021-10-17 17:59 UTC
Labels: bug
