### ISSUE TITLE
High CPU usage (and hicks) on dsd files with rates > 352.8 kHz

### ISSUE THREAD

**Issue by sf666** [MusicPlayerDaemon/MPD#424] opened 2018-11-13 20:23 UTC
Hi there,

I am using mpd 0.21.2 on an Armv7 quad core cpu. Playing DSD files up to a rate of 352.8 kHz work just fine. CPU usage is around 15%.

```
# cat /proc/asound/card2/stream0
McIntosh McIntosh HD USB Audio at usb-ci_hdrc.1-1, high speed : USB Audio

Playback:
  Status: Running
    Interface = 2
    Altset = 2
    Packet Size = 300
    Momentary freq = 352800 Hz (0x2c.1999)
    Feedback Format = 16.16
  Interface 2
    Altset 1
    Format: S16_LE
    Channels: 2
    Endpoint: 3 OUT (ASYNC)
    Rates: 32000, 44100, 48000, 88200, 96000, 176400, 192000, 352800, 384000
    Data packet interval: 125 us
  Interface 2
    Altset 2
    Format: S24_3LE
    Channels: 2
    Endpoint: 3 OUT (ASYNC)
    Rates: 32000, 44100, 48000, 88200, 96000, 176400, 192000, 352800, 384000
    Data packet interval: 125 us
  Interface 2
    Altset 3
    Format: S32_LE
    Channels: 2
    Endpoint: 3 OUT (ASYNC)
    Rates: 32000, 44100, 48000, 88200, 96000, 176400, 192000, 352800, 384000
    Data packet interval: 125 us
```

Playing files at 384 kHz delivers high CPU usage >100% and playback error (hicks every few seconds)

```
# cat /proc/asound/card2/stream0
McIntosh McIntosh HD USB Audio at usb-ci_hdrc.1-1, high speed : USB Audio

Playback:
  Status: Running
    Interface = 2
    Altset = 2
    Packet Size = 300
    Momentary freq = 384000 Hz (0x30.0000)
    Feedback Format = 16.16
  Interface 2
    Altset 1
    Format: S16_LE
    Channels: 2
    Endpoint: 3 OUT (ASYNC)
    Rates: 32000, 44100, 48000, 88200, 96000, 176400, 192000, 352800, 384000
    Data packet interval: 125 us
  Interface 2
    Altset 2
    Format: S24_3LE
    Channels: 2
    Endpoint: 3 OUT (ASYNC)
    Rates: 32000, 44100, 48000, 88200, 96000, 176400, 192000, 352800, 384000
    Data packet interval: 125 us
  Interface 2
    Altset 3
    Format: S32_LE
    Channels: 2
    Endpoint: 3 OUT (ASYNC)
    Rates: 32000, 44100, 48000, 88200, 96000, 176400, 192000, 352800, 384000
    Data packet interval: 125 us
```
I tried to raise the period time in mpd.conf. I got some minor sound-improvements (less hicks).

```
audio_output {
        type              	"alsa"
        name              	"MA"
        device            	"hw:Audio"
	auto_resample   	"no"
	auto_channels   	"no"
	auto_format     	"no"
	dsd_usb 		"no"
	mixer_type      	"none"  
	replay_gain_handler	"none"
	dop			"no"
	buffer_time		"15000000"
	period_time		"20000000"
}
```

Has someone a clue, if it is a hardware or software issue?

**Comment by sf666** [comment] 2018-11-14 07:45
I might have found the reason for high cpu load:

mpd.log
```
decoder_thread: probing plugin dsf
decoder: audio_format=dsd128:2, seekable=true
alsa_output: opened hw:Audio type=HW
alsa_output: buffer: size=96..174762 time=250..455110
alsa_output: period: size=48..87381 time=125..227555
alsa_output: format=S24_3LE (Signed 24 bit Little Endian in 3bytes)
alsa_output: buffer_size=174762 period_size=87381
output: opened "MA" (alsa) audio_format=384000:24:2
libsamplerate: setting samplerate conversion ratio to 0.54
output: converting in=dsd128:2 -> f=dsd128:2 -> out=384000:24:2
```

Looks like the file is being converted (resulting in high CPU load), even though I have no clue why the conversion takes place, because the USB DAC is able to handle DSD128 natively.

**Comment by MaxKellermann** [comment] 2018-11-14 07:56
But does the driver know this?
To analyze high load, I need a `perf report`.

**Comment by MaxKellermann** [comment] 2018-11-14 12:43
Both of your logs show that your device driver refuses to play DSD.
The second one doesn't need to resample because DSD-to-PCM conversion of DSD64 results in 352.8 kHz, which your device supports. However, DSD128 would require 705.6 kHz, which your device does not support, so MPD asks the driver to choose the next best supported sample rate, which is 384 kHz. And so MPD needs to resample.
It would be possible that the resampler you configured needs more CPU power than you have, but I can't tell until you upload the perf report.

**Comment by MaxKellermann** [comment] 2018-11-14 12:45
Closing this bug report because I assume the CPU usage is caused by your resampler. If you post data which proves something else, I'll reopen it.

**Closed by MaxKellermann** 2018-11-14 12:45 UTC

**Comment by sf666** [comment] 2018-11-14 13:31
Probably you're right. The CPU load comes from the resampling ...
