### ISSUE TITLE
MPD Bad URL Reporting

### ISSUE THREAD

**Issue by trex101** [MusicPlayerDaemon/MPD#1763] opened 2023-03-14 17:57 UTC
I use mpd/mpc in my internet radio application. I notice that some broken URLs won't play in mpd yet no error is thrown; wondering if there's a way these dead URLs can throw an error reliably. Or perhaps someone knows how mpd detects good vs. bad URLs, which may also help in finding a more accurate way to flag a bad URL. 
Example of a good URL:  https://stream.wbez.ord/wbez128.mp3
Example of a bad URL but mpd reports it as good: http://open.live.bbc.uk/mediaselector/55/select/version/2.0/mediaset/http-icy-mp3

**Comment by MaxKellermann** [comment] 2023-03-14 21:49
Duplicate of https://github.com/MusicPlayerDaemon/MPD/issues/1762 and still incomplete

**Closed by MaxKellermann** 2023-03-14 21:49 UTC
