### ISSUE TITLE
mpd crashes upon pressing play in ncmpc

### ISSUE THREAD

**Issue by emmatebibyte** [MusicPlayerDaemon/MPD#1562] opened 2022-07-04 16:48 UTC
### Describe the bug

mpd crashes upon pressing play in ncmpc

## Expected Behavior

mpd does not segfault

## Actual Behavior

mpd crashes upon pressing play in ncmpc

## Version

Music Player Daemon 0.23.7 (0.23.7)

## Configuration

```
music_directory		"~/Music"
playlist_directory		"~/.config/mpd/playlists"
db_file			"~/.config/mpd/database"
log_file			"~/.config/mpd/log"
pid_file			"~/.config/mpd/pid"
state_file			"~/.config/mpd/state"
sticker_file			"~/.config/mpd/sticker.sql"
user				"emma"
bind_to_address		"any"
bind_to_address		"~/.config/mpd/socket"
port				"6600"
log_level			"notice"
restore_paused "yes"
save_absolute_paths_in_playlists	"yes"
metadata_to_use	"artist,album,title,track,name,genre,date,composer,performer,disc"
auto_update	"yes"
input {
        plugin "curl"
}
audio_output {
        type            "pipewire"
        name            "PipeWire Sound Server"
}
audio_output {
	type		"httpd"
	name		"Emma's MPD Stream"
	encoder		"vorbis"		# optional, vorbis or lame
	port		"8000"
	bitrate		"320"			# do not define if quality is defined
	format		"44100:16:2"
	max_clients	"0"			# optional 0=no limit
}
replaygain			"auto"
replaygain_limit		"yes"
volume_normalization		"no"
filesystem_charset		"UTF-8"
```

## Log

```
config_file: loading file /home/emma/.config/mpd/mpd.conf
Jul 04 12:40 : server_socket: bind to '0.0.0.0:6600' failed (continuing anyway, because binding to '[::]:6600' succeeded): Failed to bind socket: Address already in use
Jul 04 12:40 : path: SetFSCharset: fs charset is
Jul 04 12:40 : libsamplerate: libsamplerate converter 'Fastest Sinc Interpolator'
Jul 04 12:40 : vorbis: Xiph.Org libVorbis 1.3.7
Jul 04 12:40 : opus: libopus 1.3.1
Jul 04 12:40 : sndfile: libsndfile-1.1.0
Jul 04 12:40 : hybrid_dsd: The Hybrid DSD decoder is disabled because it was not explicitly enabled
Jul 04 12:40 : simple_db: reading DB
Jul 04 12:40 : input: Input plugin 'qobuz' is not configured: No Qobuz app_id configured
Jul 04 12:40 : curl: version 7.84.0
Jul 04 12:40 : curl: with OpenSSL/1.1.1p
fish: Job 1, 'mpd --no-daemon --verbose' terminated by signal SIGSEGV (Address boundary error)
```

Backtrace:
```
emma@noire-carnation ~ [1]> gdb --args mpd --stderr --no-daemon --verbose
GNU gdb (GDB) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from mpd...
(No debugging symbols found in mpd)
(gdb) run
Starting program: /usr/bin/mpd --stderr --no-daemon --verbose
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
config_file: loading file /home/emma/.config/mpd/mpd.conf
server_socket: bind to '0.0.0.0:6600' failed (continuing anyway, because binding to '[::]:6600' succeeded): Failed to bind socket: Address already in use
path: SetFSCharset: fs charset is
libsamplerate: libsamplerate converter 'Fastest Sinc Interpolator'
vorbis: Xiph.Org libVorbis 1.3.7
opus: libopus 1.3.1
sndfile: libsndfile-1.1.0
hybrid_dsd: The Hybrid DSD decoder is disabled because it was not explicitly enabled
simple_db: reading DB
input: Input plugin 'qobuz' is not configured: No Qobuz app_id configured
curl: version 7.84.0
curl: with OpenSSL/1.1.1p
[New Thread 0x7fffe2548640 (LWP 6877)]
[New Thread 0x7fffe1d47640 (LWP 6878)]
event: RTIOThread could not get realtime scheduling, continuing anyway: sched_setscheduler failed: Operation not permitted
state_file: Loading state file /home/emma/.config/mpd/state
inotify: initializing inotify
inotify: watching music directory
client: [0] opened from [::1]:44202
client: [0] process command list
client: process command "tagtypes "all""
client: command returned 0
client: process command "tagtypes"
client: command returned 0
client: [0] process command list returned 0
client: [0] process command list
client: process command "tagtypes "clear""
client: command returned 0
client: process command "tagtypes enable Artist Album AlbumArtist Title Track Name Genre Date Composer Performer Comment Disc Work Conductor"
client: command returned 0
client: [0] process command list returned 0
client: [0] process command "status"
client: [0] command returned 0
client: [0] process command "playlistinfo"
client: [0] command returned 0
client: [0] process command "idle"
client: [0] command returned 1
client: [1] opened from [::1]:44214
client: [1] process command list
client: process command "status"
client: command returned 0
client: process command "replay_gain_status"
client: command returned 0
client: [1] process command list returned 0
client: [1] closed
client: [2] opened from [::1]:44220
client: [2] process command list
client: process command "status"
client: command returned 0
client: process command "replay_gain_status"
client: command returned 0
client: [2] process command list returned 0
client: [2] closed
client: [0] process command "lsinfo """
client: [0] command returned 0
client: [0] process command "idle"
client: [0] command returned 1
client: [3] opened from [::1]:54990
client: [3] process command list
client: process command "status"
client: command returned 0
client: process command "replay_gain_status"
client: command returned 0
client: [3] process command list returned 0
client: [3] closed
client: [4] opened from [::1]:54992
client: [4] process command list
client: process command "status"
client: command returned 0
client: process command "replay_gain_status"
client: command returned 0
client: [4] process command list returned 0
client: [4] closed
client: [0] process command "lsinfo "dylazy""
client: [0] command returned 0
client: [0] process command "idle"
client: [0] command returned 1
client: [5] opened from [::1]:52266
client: [5] process command list
client: process command "status"
client: command returned 0
client: process command "replay_gain_status"
client: command returned 0
client: [5] process command list returned 0
client: [5] closed
client: [0] process command "addid "dylazy/seanie.mp3""
client: [0] command returned 0
client: [0] process command "playid "1""
playlist: play 0:"dylazy/seanie.mp3"
[New Thread 0x7fffe1546640 (LWP 6955)]
[New Thread 0x7fffe0d45640 (LWP 6956)]
client: [0] command returned 0
client: [0] process command "idle"
client: [0] command returned 1
client: [0] process command "status"
client: [0] command returned 0
client: [0] process command "playlistinfo"
client: [0] command returned 0
client: [0] process command "idle"
client: [0] command returned 1
decoder_thread: probing plugin mad
decoder: audio_format=44100:24:2, seekable=true
client: [0] process command "status"
[New Thread 0x7fffd3fff640 (LWP 6957)]
output: OutputThread could not get realtime scheduling, continuing anyway: sched_setscheduler failed: Operation not permitted
[New Thread 0x7fffd37fe640 (LWP 6958)]
output: OutputThread could not get realtime scheduling, continuing anyway: sched_setscheduler failed: Operation not permitted
[New Thread 0x7fffd2ffd640 (LWP 6959)]
server_socket: bind to '0.0.0.0:8000' failed (continuing anyway, because binding to '[::]:8000' succeeded): Failed to bind socket: Address already in use
[New Thread 0x7fffd27be640 (LWP 6960)]
output: opened "PipeWire Sound Server" (pipewire) audio_format=44100:24:2
output: opened "Emma's MPD Stream" (httpd) audio_format=44100:f:2
output: converting in=44100:24:2 -> f=44100:24:2 -> out=44100:f:2
replay_gain: replay gain mode has changed off->album
replay_gain: replay gain mode has changed off->album
replay_gain: scale=1
client: [0] command returned 0
replay_gain: scale=1

Thread 8 "PipeWire Sound " received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffd2ffd640 (LWP 6959)]
0x00007ffff2f51f0b in ?? () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff2f50f0b in  () at /usr/lib/libc.so.6
#1  0x00005555556145ce in  ()
#2  0x00007ffff545a91f in  () at /usr/lib/libpipewire-0.3.so.0
#3  0x00007ffff543c031 in  () at /usr/lib/libpipewire-0.3.so.0
#4  0x00007fffd1f5d51f in  () at /usr/lib/spa-0.2/audioconvert/libspa-audioconvert.so
#5  0x00007fffd1f70139 in  () at /usr/lib/spa-0.2/audioconvert/libspa-audioconvert.so
#6  0x00007fffd1f98cc9 in  () at /usr/lib/spa-0.2/audioconvert/libspa-audioconvert.so
#7  0x00007fffd1f5e101 in  () at /usr/lib/spa-0.2/audioconvert/libspa-audioconvert.so
#8  0x00007ffff543d2e0 in pw_impl_node_for_each_param () at /usr/lib/libpipewire-0.3.so.0
#9  0x00007ffff545bc4d in  () at /usr/lib/libpipewire-0.3.so.0
#10 0x00007ffff542ff03 in  () at /usr/lib/libpipewire-0.3.so.0
#11 0x00007ffff54387e6 in  () at /usr/lib/libpipewire-0.3.so.0
#12 0x00007fffd1f6460e in  () at /usr/lib/spa-0.2/audioconvert/libspa-audioconvert.so
#13 0x00007fffd1f69b1e in  () at /usr/lib/spa-0.2/audioconvert/libspa-audioconvert.so
#14 0x00007fffd1f78132 in  () at /usr/lib/spa-0.2/audioconvert/libspa-audioconvert.so
#15 0x00007fffd1f6363d in  () at /usr/lib/spa-0.2/audioconvert/libspa-audioconvert.so
#16 0x00007fffe0043b9b in  () at /usr/lib/pipewire-0.3/libpipewire-module-client-node.so
#17 0x00007fffe0052e35 in  () at /usr/lib/pipewire-0.3/libpipewire-module-client-node.so
#18 0x00007fffe008bf84 in  () at /usr/lib/pipewire-0.3/libpipewire-module-protocol-native.so
#19 0x00007fffe008c620 in  () at /usr/lib/pipewire-0.3/libpipewire-module-protocol-native.so
#20 0x00007ffff7fa6e4d in  () at /usr/lib/spa-0.2/support/libspa-support.so
#21 0x00007ffff545fffa in  () at /usr/lib/libpipewire-0.3.so.0
--Type <RET> for more, q to quit, c to continue without paging--c
#22 0x00007ffff2e7d54d in  () at /usr/lib/libc.so.6
#23 0x00007ffff2f02874 in clone () at /usr/lib/libc.so.6
```

**Comment by MaxKellermann** [comment] 2022-07-04 17:00
The backtrace is still missing.

**Comment by emmatebibyte** [comment] 2022-07-04 17:15
sorry. copied it in two separate parts.

**Comment by MaxKellermann** [comment] 2022-07-04 17:17
Duplicate of https://github.com/MusicPlayerDaemon/MPD/issues/1558

**Closed by MaxKellermann** 2022-07-04 17:17 UTC
Labels: waiting
