### ISSUE TITLE
When unpausing, there is a 1 second delay before audio resumes with fifo visualizer

### ISSUE THREAD

**Issue by Fxzzi** [MusicPlayerDaemon/MPD#2052] opened 2024-05-21 08:36 UTC
### Describe the bug

When pausing and then playing music again, there is a small delay before the audio begins to play again. The song is playing in between this time, as I can see the visualizer on ncmpcpp moving before the audio comes back. This happens across two devices, a custom built PC with a Ryzen 5 5600x and my laptop with a Ryzen 5 7530U. Both devices are running pipewire.

## Expected Behavior

I expect the audio to resume instantly, like how it does with fifo visualizer disabled. I think some other issues are also related to this, including random popping audio and random cutting out of audio for a second or two.

## Actual Behavior

Instead audio only pops back in a second or so after resuming from mpd or ncmpcpp

## Version

```
Music Player Daemon 0.23.15 (v0.23.15)
Copyright 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2021 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple proxy upnp

Storage plugins:
 local udisks nfs curl

Neighbor plugins:
 upnp udisks

Decoders plugins:
 [mad] mp3 mp2
 [mpg123] mp3
 [vorbis] ogg oga
 [oggflac] ogg oga
 [flac] flac
 [opus] opus ogg oga
 [sndfile] wav aiff aif au snd paf iff svx sf voc w64 pvf xi htk caf sd2
 [audiofile] wav au aiff aif
 [dsdiff] dff
 [dsf] dsf
 [hybrid_dsd] m4a
 [faad] aac
 [mpcdec] mpc
 [wavpack] wv
 [openmpt] mptm mod s3m xm it 669 amf ams c67 dbm digi dmf dsm dtm far imf ice j2b m15 mdl med mms mt2 mtm nst okt plm psm pt36 ptm sfx sfx2 st26 stk stm stp ult wow gdm mo3 oxm umx xpk ppm mmcmp
 [modplug] 669 amf ams dbm dfm dsm far it med mdl mod mtm mt2 okt s3m stm ult umx xm
 [mikmod] amf dsm far gdm imf it med mod mtm s3m stm stx ult uni xm
 [sidplay] sid mus str prg P00
 [wildmidi] mid
 [fluidsynth] mid
 [gme] ay gbs gym hes kss nsf nsfe rsn sap spc vgm vgz
 [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 adx afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tak tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve rtp:// rtsp:// rtsps://
 [pcm]

Filters:
 libsamplerate soxr

Tag plugins:
 id3tag

Output plugins:
 shout null fifo pipe alsa ao oss openal solaris pipewire pulse jack httpd snapcast recorder

Encoder plugins:
 null vorbis opus lame twolame wave flac

Archive plugins:
 [bz2] bz2
 [zzip] zip
 [iso] iso

Input plugins:
 file io_uring archive alsa qobuz curl ffmpeg nfs mms cdio_paranoia

Playlist plugins:
 extm3u m3u pls xspf asx rss soundcloud flac cue embcue

Protocols:
 file:// alsa:// cdda:// ftp:// ftps:// gopher:// hls+http:// hls+https:// http:// https:// mms:// mmsh:// mmst:// mmsu:// nfs:// qobuz:// rtmp:// rtmpe:// rtmps:// rtmpt:// rtmpte:// rtmpts:// rtp:// rtsp:// rtsps:// scp:// sftp:// smb:// srtp://

Other features:
 avahi dbus udisks epoll icu inotify ipv6 systemd tcp un
```

## Configuration

```
# Required files
db_file            "~/.local/share/mpd/database"
log_file           "~/.local/share/mpd/log"

# Optional
music_directory    "~/Music"
playlist_directory "~/.local/share/mpd/playlists"
pid_file           "~/.local/share/mpd/pid"
state_file         "~/.local/share/mpd/state"
sticker_file       "~/.local/share/mpd/sticker.sql"
bind_to_address    "127.0.0.1"

audio_output {
        type            "pipewire"
        name            "PipeWire Sound Server"
}

audio_output {
    type                    "fifo"
    name                    "fifo Visualizer"
    path                    "/tmp/mpd.fifo"
}
```

## Log

Log doesn't show anything useful:

```
config_file: loading file /home/faaris/.config/mpd/mpd.conf
May 21 09:33 : libsamplerate: libsamplerate converter 'Fastest Sinc Interpolator'
May 21 09:33 : vorbis: Xiph.Org libVorbis 1.3.7
May 21 09:33 : opus: libopus 1.5.2
May 21 09:33 : sndfile: libsndfile-1.2.2
May 21 09:33 : hybrid_dsd: The Hybrid DSD decoder is disabled because it was not explicitly enabled
May 21 09:33 : decoder: Decoder plugin 'wildmidi' is unavailable: configuration file does not exist: /etc/timidity/timidity.cfg
May 21 09:33 : simple_db: reading DB
May 21 09:33 : input: Input plugin 'qobuz' is not configured: No Qobuz app_id configured
May 21 09:33 : curl: version 8.7.1
May 21 09:33 : curl: with OpenSSL/3.3.0
```

**Comment by naglis** [comment] 2024-05-21 08:39
Possibly related/duplicate of #1136.

**Comment by Fxzzi** [comment] 2024-05-21 08:57
> Possibly related to/duplicate of #1136.

From what I can tell, I experience this issue with visualizer disabled also. In ncmpcpp, holding down `p` to rapidly pause and unpause does infact skip time in the song. However this is an instant skip, unlike this where its a 1 second delay.

**Comment by MaxKellermann** [comment] 2024-07-05 16:57
This project does not support the ncmpcpp visualizer. This ncmpcpp feature is considered an abuse of an experimental MPD feature, and this ncmpcpp "feature" may be a reason to remove the plugin eventually.
For proper visualization, something like https://github.com/MusicPlayerDaemon/MPD/pull/1449 is needed.

**Closed by MaxKellermann** 2024-07-05 16:57 UTC
